jcifs/1.3.17.wso2v1/pom.xml
jsch/0.1.51.wso2v1/pom.xml
pom.xml

Add jcifs 1.3.17 and JSch 0.1.51 to Orbit.
https://wso2.org/jira/browse/ESBJAVA-3449

Upgraded jcifs and JSch to their latest versions

---

disruptor/3.3.0.wso2v1/pom.xml

Upgrading LMax Disruptor to newest version ( 3.3.0)

Upgrading LMax Disruptor to newest version ( 3.3.0)

---

hadoop-client/2.6.0.wso2v1/pom.xml
hbase-client/1.0.0.wso2v1/pom.xml
htrace/3.0.4.wso2v1/pom.xml
htrace/3.1.0-incubating.wso2v1/pom.xml
protobuf-java/2.5.0.wso2v1/pom.xml

Adding new bundles required for HBase Analytics Datasource implementation

New orbit bundles required for HBase Analytics

---

lucene/4.10.3.wso2v2/pom.xml

Added lucene-facets and lucene-expressions dependancies.

New lucene orbit bundle with lucene facets for carbon-analytics

---

jackson-annotations/2.6.1.wso2v1/pom.xml
jackson-core/2.6.1.wso2v1/pom.xml
jackson-databind/2.6.1.wso2v1/pom.xml

Upgraded following libraries,
jackson-annotations
jackson-core
jackson-databind

Upgrading jackson libraries to 2.6.1

---

hadoop-client/2.6.0.wso2v2/pom.xml
hbase-client/1.1.2.wso2v1/pom.xml

Change summary:
- hadoop-client: exposing services
- hbase-client: Version upgrade (1.0.0 -> 1.1.2), added DynamicImport-Package declaration to enable consumption of SPIs from hadoop-client

Adding new orbit bundles for hadoop-client and hbase-client

---

hazelcast/3.5.4.wso2v1/pom.xml

Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>

Adding Hazelcast 3.5.4

---

membrane-soa-model/1.5.0.wso2v4/pom.xml

Adding membrane-soa-model orbit  1.5.0.wso2v4 version.

---

jackson-databind/2.6.1.wso2v2/pom.xml

Revert "ESBJAVA-4640: fixing the typo issue in import datatype package"

---

storm-core/0.10.1.wso2v1/pom.xml

Signed-off-by: sajith <sajithshn@gmail.com>

Adding orbit bundle for storm version 0.10.1

---

metrics-json/pom.xml

New Orbit bundle metrics-json contains com.codahale.metrics.json packages from the 2.4.4 version of com.fasterxml.jackson.core.

Added branch metrics-json to my fork of Orbit and added new orbit bundle, metrics-json

---

spark-core_2.10/1.6.2.wso2v2/pom.xml

Added the embedded dependency to new metrics-json orbit bundle.

Added new spark-core version

---

saxon/9.7.0.wso2v1/pom.xml

This adds version 9.7.0-8 Saxon-HE.

Adding Saxon-HE orbit

---

tomcat-catalina-ha/7.0.73.wso2v1/pom.xml
tomcat-el-api/7.0.73.wso2v1/pom.xml
tomcat-jsp-api/7.0.73.wso2v1/pom.xml
tomcat-servlet-api/7.0.73.wso2v1/pom.xml
tomcat-websocket/7.0.73.wso2v1/pom.xml
tomcat/7.0.73.wso2v1/pom.xml
tomcat/7.0.73.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

There are new security fixes which are available for tomcat 7.0.73. This version upgrade is created to address those. For more details on what change in tomcat 7.0.73 visit following links.
[1].https://tomcat.apache.org/security-7.html#Fixed_in_Apache_Tomcat_7.0.73
[2].http://tomcat.apache.org/tomcat-7.0-doc/changelog.html

Added orbit module for tomcat version upgrade from 7.0.70wso2v1 to 7.0.73wso2v1

---

quartz/2.3.0.wso2v2/pom.xml

This PR fixes the issue the previous version had with resolving dependencies of the bundle.

Fix dependency resolution issue in Quartz 2.3.0.wso2v1

---

docker-client/1.2.2.wso2v1/pom.xml
kubernetes-client/2.5.2.wso2v3/pom.xml
logging-interceptor/3.8.0.wso2v2/pom.xml
okhttp-ws/3.4.2.wso2v2/pom.xml
okhttp/3.8.0.wso2v2/pom.xml

This PR fixes the okhttp3 exports in the okhttp, okhttp-ws, and okhttp logging-intercepter bundles.

K8s Client - Fix okhttp3 exports

---

json-schema-validator-all/2.2.6.wso2v3/pom.xml

adding org.mozilla.javascript osgi import to json schema validator and increase the version
Related JIRA : https://wso2.org/jira/browse/ESBJAVA-5079

Add org.mozilla.javascript osgi import to json-schema-validator-all and create new version

---

httpclient/4.3.6.wso2v1/pom.xml

> orbit for httpclient 4.3.6
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Adding httpclient 4.3.6.wso2v1

---

pom.xml
tranql-connector/1.1.0.wso2v1/pom.xml

Created new tranql-connector orbit.

---

tranql-connector/1.1.0.wso2v1/pom.xml

Changed the orbit version to match the original version.

---

jdbc-pool/7.0.81.wso2v2/pom.xml

adding jdbc-pool 7.0.81.wso2v2

---

reflections/0.9.11.wso2v1/pom.xml

Orbit bundle for reflection to use in msf4j 
Upgrade the reflection version to latest.

resolves #293 orbit bundle for reflection 0.9.11

---

disruptor/3.3.7.wso2v1/pom.xml

Add disruptor 3.3.7 orbit bundle to use for the MB4 components osgificattion requirement
> Link to the PR for changes to the …

add disruptor 3.3.7 orbit bundle

---

openid4java/1.0.0.wso2v3/pom.xml

Expanding the import version range of http.client to support newer versions of identity extensions.
Expanding the import version range of http.client to support newer versions of identity extensions.
> Link to the PR for changes to …

Expanding the import version range of http.client

---

netty/4.0.39.wso2v1/pom.xml

upgrade netty-all to version above 4.0.37.Final to overcome vulnerability CVE-2016-4970
> Link to the PR for changes to the …

add orbit for netty-all 4.0.39.Final

---

nimbus/5.4.0.wso2v1/pom.xml

Add latest nimbus-jose-jwt orbit. 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

add 5.4.0.wso2v1 orbit

---

opensaml/2.6.6.wso2v2/pom.xml

Add latest opensaml orbit
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

add opensaml 2.6.6 orbit

---

poi-ooxml/3.17.0.wso2v1/pom.xml
poi-scratchpad/3.17.0.wso2v1/pom.xml
poi/3.17.0.wso2v1/pom.xml

add apache poi 3.17 orbit bundle
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

add apache poi 3.17 orbit bundle

---

cxf/2.7.16.wso2v1/pom.xml
pom.xml

> This is to fix vulnerabilities such as CVE-2016-8739

Removed vulnerable packages from cxf plugin

---

pom.xml

> Add file-upload module to the orbit parent

Added file-upload module to the parent

---

tomcat-catalina-ha/7.0.85.wso2v1/pom.xml
tomcat-el-api/7.0.85.wso2v1/pom.xml
tomcat-jsp-api/7.0.85.wso2v1/pom.xml
tomcat-servlet-api/7.0.85.wso2v1/pom.xml
tomcat/7.0.85.wso2v1/pom.xml
tomcat/7.0.85.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

This PR contains changes to upgrade the tomcat version to 7.0.85 for kernel release. …

Upgrade tomcat version to 7.0.85

---

commons-collections4/4.1.wso2v1/pom.xml

This is to add an orbit bundle for following dependency
<dependency>
<groupId>org.apache.commons</groupId>
<artifactId>commons-collections4</artifactId>
<version>4.1</version>
</dependency>
This dependency is required when upgrading the apache poi version to 3.17.0
> Link(s) to …

Add orbit bundle for commons-collections4 4.1

---

json-schema-validator-all/2.2.6.wso2v4/pom.xml

Add json-schema-validator-all 2.2.6.wso2v4 with com.google.common version range [19.0.0,20.0.0]. This is required to upgrade guava version in carbon-mediation.
> Brief description of the new feature or bug fix as it …

Add json-schema-validator-all 2.2.6.wso2v4

---

nimbus/5.8.0.wso2v1/pom.xml

Part of fix for https://github.com/wso2/product-is/issues/3140

Introduce nimbus-jose-jwt version 5.8

---

httpclient/4.3.1.wso2v3/pom.xml
httpclient/4.3.6.wso2v2/pom.xml
openid4java/1.0.0.wso2v4/pom.xml

> Add new version of httpclient and openid4java with updated codec-common import range [1.4,2.0)
refer to mail "Updating common codec version to 1.10.wso2v1 in IS 5.6"
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Add new version of httpclient and openid4java

---

damnhandy-uri-template/2.1.6.wso2v1/pom.xml

This is to add an orbit bundle for following dependency
damnhandy-uri-template 2.1.6.wso2v1
> Link to the PR for changes to the …

Add orbit bundle for damnhandy-uri-template 2.1.6

---

joda-time/2.9.4.wso2v1/pom.xml

This is to add an orbit bundle for following dependency
joda-time 2.9.4.wso2v1 …

Add orbit bundle for joda-time 2.9.4.wso2v1

---

damnhandy-uri-template/2.1.6.wso2v1/pom.xml

This is to add distributionManagement and repositories to the pom file of the damnhandy-uri-template/2.1.6.wso2v1
> Link to the …

Adding distributionManagement and repositories

---

damnhandy-uri-template/2.1.6.wso2v2/pom.xml

Upgrade damnhandy-uri-template version …

Upgrade damnhandy-uri-template version

---

olingo-server/4.4.0wso2v1/pom.xml

Add olingo 4.4.0 bundle

---

httpasyncclient/4.0.2.wso2v1/pom.xml

> Add orbit bundle for httpasyncclient

Add httpasyncclient orbit bundle

---

xerces/2.12.0.wso2v1/pom.xml

Apache Xerces2 Java allows remote attackers to cause a denial of service (CPU consumption) via a crafted message to an XML service, which triggers hash table collisions.
This is fixed in xereces 2.12.0 version
> Link(s) to product documentation that addresses the changes of this PR. …

Upgrade xercesimpl version

---

membrane-soa-model/1.6.0.wso2v1/pom.xml

> upgrade the dependency library version

Add 1.6.0 orbit for membrane-soa-model

---

swagger-inflector/1.0.15.wso2v1/pom.xml
swagger-inflector/1.0.16.wso2v1/pom.xml

This library is used to generate sample JSON schema from the swagger definition …

Add swagger-inflector 1.0.16

---

swagger-inflector/1.0.16.wso2v1/pom.xml

Change swagger-inflector orbit version  1.0.15 to 1.0.16

---

jsch/0.1.51.wso2v1/pom.xml

Fixes: wso2/product-ei#2718
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Upgrade jsch version to 0.1.54 for product-ei/issues/2718

---

lucene/5.5.5.wso2v1/pom.xml
solr/5.5.5.wso2v1/pom.xml

Added solr and lucene 5.5.5

---

commons-text/1.6.wso2v1/pom.xml
pom.xml

Add commons-text 1.6 orbit

---

pom.xml

This adds commons-text parent module

Add commons-text parent module

---

re2j/1.2.wso2v1/pom.xml

This library used for the pattern matching in API regex threat protector to improve its performance.

re2j third party library

---

bcprov/1.60.0.wso2v1/pom.xml
pom.xml

> Adds the 1.60.0.wso2v1 version for bcprov bundle.

Add bcprov 1.60.0.wso2v1

---

jsonpath/2.4.0.wso2v2/pom.xml

> add missing dependencies. Migrating fix done in https://github.com/wso2-support/orbit/pull/84/files to this version

Add jasonpath 2.4.0.wso2v2

---

pom.xml
tomcat-catalina-ha/7.0.93.wso2v1/pom.xml
tomcat-el-api/7.0.93.wso2v1/pom.xml
tomcat-jsp-api/7.0.93.wso2v1/pom.xml
tomcat-servlet-api/7.0.93.wso2v1/pom.xml
tomcat-websocket/7.0.93.wso2v1/pom.xml
tomcat/7.0.93.wso2v1/pom.xml
tomcat/7.0.93.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

This PR contains changes to upgrade the tomcat version to 7.0.93

Upgrade tomcat to version 7.0.93

---

activation/1.1.1.wso2v2/pom.xml
pom.xml

> activation 1.1.1.wso2v1 has missing exported com.sun.activation components. Adding it in this version

Add javax.activation 1.1.1.wso2v2

---

libthrift/0.12.0.wso2v1/pom.xml

Add libthrift 0.12.0

---

commons-codec/1.12.0.wso2v1/pom.xml
pom.xml

This PR adds orbit bundle for latest commons-codec version

Add commons-codec 1.12

---

olingo-server/4.4.0wso2v2/pom.xml

Add odata server 4.4.0wso2v2 version

---

disruptor/3.4.2.wso2v1/pom.xml
pom.xml

Add disruptor v3.4.2 to orbit

---

json-schema-validator-all/2.2.6.wso2v6/pom.xml

Update json-schema validator all

---

waffle/1.6.wso2v6/pom.xml

This modifies the guava import version range (com.google.common.version)

waffle 1.6.wso2v6

---

gogoproto-java/1.0.0.wso2v1/pom.xml
gogoproto-java/1.0.0.wso2v1/src/main/proto/gogoproto/gogo.proto
pom.xml

> To add gogoproto-java version 1.0.0.wso2v1 as the orbit bundle.

Add gogoproto-java 1.0.0.wso2v1

---

openapi-generator/4.0.1.wso2v1/pom.xml
swagger-parser/2.0.13.OpenAPITools.wso2v1/pom.xml

Add openapitools generator and parser dependencies.  …

Add openapitools generator and swagger parser.

---

httpcore/4.4.11-wso2v1/pom.xml

Add httpcore-4.4.11 to the orbit repo

Add httpcore-4.4.11 to the orbit repo

---

openapi-generator/4.0.1.wso2v2/pom.xml

Add open api tools generator v4.0.1.wso2v2 fixing an issue in the previous version. (4.0.1.wso2v1)

Add openapi-generator v4.0.1.wso2v2

---

openjpa-all/2.2.2.wso2v2/pom.xml

Fix openjpa-all

---

openjpa-all/2.2.2.wso2v2/pom.xml

Release openjpa-all orbit
Release openjpa-all orbit
Fix issues in the pom file
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Fix issues in openjpa-all pom file

---

nimbus/7.3.0.wso2v1/pom.xml

Adding orbit bundle for nimbusds-jose-jwt 7.3 jar
Part of https://github.com/wso2/product-is/issues/5786

Add nimbusds 7.3 orbit

---

opensaml/2.6.6.wso2v2/pom.xml
opensaml/2.6.6.wso2v3/pom.xml

> Add opensaml 2.6.6.wso2v3
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Add opensaml 2.6.6.wso2v3

---

activation/1.1.1.wso2v1/pom.xml
json-schema-validator-all/2.2.6.wso2v7/pom.xml

> Update dependencies for javax.mail in json-scheme-validator-all pom

Update javax mail dependecies for jdk 11

---

h2/1.4.199.wso2v1/pom.xml
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2ConsoleServiceActivator.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2/1.4.199.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

Add H2 1.4.199.wso2v1

---

activation/1.1.1.wso2v1/pom.xml
activation/1.1.1.wso2v3/pom.xml

Revert changes for activation v1 and move it to v3

---

graphQL/13.0-wso2v1/pom.xml

This library used for graphQL feature

Add graphql-java library with all dependencies

---

swagger-codegen/2.3.1.wso2v1/pom.xml

Reverts wso2/orbit#383
Need to add to new release

Revert "Exclude swagger parser from export packages in swagger-codegen"

---

tomcat-catalina-ha/9.0.21.wso2v1/pom.xml
tomcat-el-api/9.0.21.wso2v1/pom.xml
tomcat-jsp-api/9.0.21.wso2v1/pom.xml
tomcat-servlet-api/9.0.21.wso2v1/pom.xml
tomcat-websocket/9.0.21.wso2v1/pom.xml
tomcat/9.0.21.wso2v1/pom.xml
tomcat/9.0.21.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add Tomcat 9 orbit

---

tomcat-catalina-ha/9.0.24.wso2v1/pom.xml
tomcat-el-api/9.0.24.wso2v1/pom.xml
tomcat-jsp-api/9.0.24.wso2v1/pom.xml
tomcat-servlet-api/9.0.24.wso2v1/pom.xml
tomcat-websocket/9.0.24.wso2v1/pom.xml
tomcat/9.0.24.wso2v1/pom.xml
tomcat/9.0.24.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.24

---

hazelcast/3.12.2.wso2v1/pom.xml

add hazelcast 3.12.2

---

tomcat-catalina-ha/9.0.22.wso2v1/pom.xml
tomcat-el-api/9.0.22.wso2v1/pom.xml
tomcat-jsp-api/9.0.22.wso2v1/pom.xml
tomcat-servlet-api/9.0.22.wso2v1/pom.xml
tomcat-websocket/9.0.22.wso2v1/pom.xml
tomcat/9.0.22.wso2v1/pom.xml
tomcat/9.0.22.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add Tomcat update v9.0.22

---

ua-parser/1.3.0.wso2v2/pom.xml

Related https://github.com/wso2/carbon-identity-framework/pull/2404

Add ua-parser 1.3.0.wso2v2

---

ua-parser/1.3.0.wso2v2/pom.xml

Related https://github.com/wso2/orbit/pull/392

Remove unwanted properties from ua-parser 1.3.0.wso2v2 POM file

---

activiti-all/5.23.0.wso2v1/pom.xml

> This PR will create the orbit bundle for activiti version upgrade 5.23.0.

Adding orbit bundle for activiti 5.23.0 version

---

graphQL/13.0-wso2v2/pom.xml

> Additions made so as to implement fine-grained access control to graphQL APIs.

Some alterations under the exported package for graphQL

---

awslambda/1.11.253.wso2v1/pom.xml
awslambda/pom.xml

To add a custom bundle that wraps aws-java-sdk-core and aws-java-sdk-lambda along with httpclient 4.5.2.

Add awslambda-1.11.253.wso2v1 module

---

jsch/0.1.55.wso2v1/pom.xml

The purpose of this PR is to add Jsch-0.1.55.wso2v1 module
Fix https://github.com/wso2/product-ei/issues/4343

Add Jsch-0.1.55.wso2v1 module

---

jaeger-client/0.32.0.wso2v1/pom.xml

Add Jaeger Client

---

antlr/4.7.2.wso2v1/pom.xml

Add antlr 4.7.2 related library modules

Add antlr 4.7.2 related library modules

---

js/1.7.0.R5.wso2v1/pom.xml

Add distributionManagement element to the js/1.7.0.R5.wso2v1/pom.xml.

Adding distributionManagement element to the pom.xml

---

handlebars/4.0.7.wso2v1/pom.xml

Add handlebars 4.0.7 related library modules

Add handlebars 4.0.7 related library modules

---

commons-compress/1.18.0.wso2v1/pom.xml
kubernetes-client/4.6.4.wso2v1/pom.xml
okhttp/4.2.0.wso2v1/pom.xml
okio/2.4.0.wso2v1/pom.xml

> Bundling the dependencies required to connect to  kubernetes/openshift clusters …

Bundling dependencies for kubernetes/openshift clients

---

swagger-inflector/2.0.5.wso2v1/pom.xml

Adding swagger-inflector 2.0.5.wso2v1

---

jaeger-client/0.32.0.wso2v2/pom.xml

add jaeger-client 0.32.wso2v2

---

tomcat-catalina-ha/9.0.34.wso2v1/pom.xml
tomcat-el-api/9.0.34.wso2v1/pom.xml
tomcat-jsp-api/9.0.34.wso2v1/pom.xml
tomcat-servlet-api/9.0.34.wso2v1/pom.xml
tomcat-websocket/9.0.34.wso2v1/pom.xml
tomcat/9.0.34.wso2v1/pom.xml
tomcat/9.0.34.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Added tomcat/9.0.34

---

tomcat-catalina-ha/9.0.34.wso2v1/pom.xml
tomcat-el-api/9.0.34.wso2v1/pom.xml
tomcat-jsp-api/9.0.34.wso2v1/pom.xml
tomcat-servlet-api/9.0.34.wso2v1/pom.xml
tomcat-websocket/9.0.34.wso2v1/pom.xml
tomcat/9.0.34.wso2v1/pom.xml

fixed versions

---

jackson-annotations/2.11.0.wso2v1/pom.xml
jackson-core/2.11.0.wso2v1/pom.xml
jackson-databind/2.11.0.wso2v1/pom.xml
jackson-dataformat/2.11.0.wso2v1/pom.xml

Upgrade Jackson libraries to 2.11.0

---

jdbc-pool/9.0.35.wso2v1/pom.xml

Upgrade jdbc-pool to 9.0.35

---

commons-collections4/4.4.wso2v1/pom.xml

Upgrade commons-collection4 to 4.4

---

asn-one/0.4.0.wso2v1/pom.xml
mbassador/1.3.2.wso2v1/pom.xml
pom.xml
smbj/0.10.0.wso2v1/pom.xml

> Add mbassador, asn-one and smbj orbit bundles

Add mbassador, asn-one and smbj orbit bundles

---

webharvest/2.0.0.wso2v4/pom.xml

Upgrade commons-email inside webharvest and release a new webharvest version

Update commons-email inside webharvest to 1.5

---

swagger-parser/2.0.14.OpenAPITools.wso2v1/pom.xml

Add latest swagger parser

---

batik/1.9.1.wso2v1/pom.xml
pom.xml

This is to fix https://github.com/wso2/product-ei/issues/5150

Upgrade Apache Batik version to 1.9.1

---

kubernetes-client/4.6.4.wso2v1/pom.xml
okhttp/4.2.0.wso2v1/pom.xml

> Bundling the dependencies required to mock the Kubernetes server to test
> Link to the PR for changes to the training content …

Update kubernetes,okhttp dependency bundles

---

asn-one/0.4.0.wso2v2/pom.xml
mbassador/1.3.2.wso2v2/pom.xml
smbj/0.10.0.wso2v2/pom.xml

> Add smb2 related dependecies.

Add smb2 related dependecies.

---

openapi-generator/4.3.1.wso2v1/pom.xml
swagger-parser/1.0.51.wso2v1/pom.xml
swagger-parser/2.0.20.wso2v1/pom.xml

Upgrade swagger dependencies

---

kubernetes-client/2.5.2.wso2v3/pom.xml
kubernetes-client/4.6.4.wso2v1/pom.xml

>updating package com.mifmif.common.regex in Kubernetes dependency bundles.
> Link to the PR for changes to the training content …

Update Kubernetes dependency bundles

---

jaeger-client/0.32.0.wso2v4/pom.xml

Add jaeger-client 0.32.0.wso2v4

---

.gitignore
commons-codec/1.14.0.wso2v1/pom.xml

Related https://github.com/wso2/product-is/issues/8042

Add commons-codec:1.14.0-wso2v1

---

snakeyaml/1.26.0.wso2v1/pom.xml

Add snakeyaml 1.26.0.wso2v1

---

openapi-generator/4.3.1.wso2v2/pom.xml

Creating a new version for openapi-generator in order to remove javax.annotation export contents

New openapi-generator version

---

httpclient/4.5.13.wso2v1/pom.xml
httpcore-nio/4.4.14.wso2v1/pom.xml
httpcore/4.4.14-wso2v1/pom.xml

Add the following latest httpcomponents orbit bundles
- httpcore : 4.4.14
- httpcore-nio : 4.4.14
- httpclient : 4.5.13

Add latest httpcomponents

---

smooks/1.5.1.wso2v3/pom.xml

Fixing the test case failing issue of MI due to a smooks dependency resolving issue.

changing smooks v3 configs

---

smooks/1.5.1.wso2v3/pom.xml

Revert "changing smooks v3 configs"

---

jaxb-api/2.3.1.wso2v2/pom.xml

Fix version error

---

yubico-webauthn/1.3.0.wso2v3/pom.xml

Fixes https://github.com/wso2/product-is/issues/11055

Fix class not found issue in webauthn

---

pom.xml
swagger-parser-v3/2.0.24.wso2v1/pom.xml

> Bundling the swagger-paser-v3 alone since swagger-parser orbit bundle
has other dependencies.

Add swagger-parser-v3 orbit bundle.

---

azure-core-amqp/1.6.0.wso2v1/pom.xml
azure-core/1.9.0.wso2v1/pom.xml
azure-messaging-eventhubs/1.6.0.wso2v1/pom.xml
reactor-core/3.3.9.wso2v1/pom.xml

Adding the following to orbit
- azure-core-amqp
- azure-core
- azure-messaging-eventhubs
- reactor-core

Added orbit bundles

---

httpclient/4.3.6.wso2v3/pom.xml

Increase httpcore import range in httpclient

---

pom.xml
swagger-request-validator/2.12.1.wso2v1/pom.xml

> to use in schema validation in WSO2 APIM …

Add latest swagger-request-validator lib as an Orbit

---

swagger-request-validator/2.12.1.wso2v1/pom.xml

> 
fix CNF issues in swagger-request-validator-2.12.1 …

 fix CNF issues in swagger-request-validator-2.12.1

---

pom.xml
swagger-request-validator/2.12.1.wso2v1/pom.xml
swagger-request-validator/2.12.1.wso2v2/pom.xml

Fix for wso2/product-apim#10393

Fix for wso2/product-apim#10393

---

bcprov/1.68.0.wso2v1/pom.xml
pom.xml

Add the 1.68.0.wso2v1 version for bcprov bundle.

Add bcprov 1.68.0.wso2v1

---

tomcat-catalina-ha/9.0.45.wso2v1/pom.xml
tomcat-el-api/9.0.45.wso2v1/pom.xml
tomcat-jsp-api/9.0.45.wso2v1/pom.xml
tomcat-servlet-api/9.0.45.wso2v1/pom.xml
tomcat-websocket/9.0.45.wso2v1/pom.xml
tomcat/9.0.45.wso2v1/pom.xml
tomcat/9.0.45.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Add tomcat 9.0.45.wso2v1

---

jdbc-pool/9.0.52.wso2v1/pom.xml
tomcat-catalina-ha/9.0.52.wso2v1/pom.xml
tomcat-el-api/9.0.52.wso2v1/pom.xml
tomcat-jsp-api/9.0.52.wso2v1/pom.xml
tomcat-servlet-api/9.0.52.wso2v1/pom.xml
tomcat-websocket/9.0.52.wso2v1/pom.xml
tomcat/9.0.52.wso2v1/pom.xml
tomcat/9.0.52.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.52.wso2v1

---

azure-messaging-servicebus/7.0.2.wso2v1/pom.xml

Add azure-messaging-servicebus dependency for publishing events to Azure Service Bus.

Add azure-messaging-servicebus 7.0.2.wso2v1

---

azure-core/1.14.0.wso2v1/pom.xml

Add azure-core dependency for publishing events to Azure Service Bus.

Add azure-core 1.14.0.wso2v1

---

azure-messaging-servicebus-sdk-all/7.3.0.wso2v1/pom.xml

Add azure-messaging-servicebus dependency for publishing events to Azure Service Bus.

Add azure-messaging-servicebus 7.3.0.wso2v1

---

azure-messaging-servicebus-sdk-all/7.3.0.wso2v3/pom.xml

This PR will add the com.azure.core.util.serializer to  azure-messaging-servicebus Added for https://github.com/wso2/orbit/pull/475
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …

Adding 7.3.0.wso2v3 for azure-messaging-servicebus-sdk-all

---

azure-messaging-servicebus-sdk-all/7.3.0.wso2v4/pom.xml

Adding 7.3.0.wso2v4 for azure-messaging-servicebus-sdk-all to import com.azure.core.util package
> Link to the PR for changes to …

Adding 7.3.0.wso2v4 for azure-messaging-servicebus-sdk-all

---

h2/1.4.200.wso2v1/pom.xml
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2ConsoleServiceActivator.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2/1.4.200.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

update h2 version to 1.4.200

---

membrane-soa-model/1.6.0.wso2v3/pom.xml

Update third party library versions (asm version range)
Related to https://github.com/wso2/product-is/issues/12479

Update asm version range

---

tomcat-el-api/9.0.52.wso2v2/pom.xml

$subject. Or else the classes does not get packed inside the bundle.
```
<Private-Package>
javax.el.*;version="3.0"
</Private-Package>
```

Create tomcat-el-api 9.0.52 bundle with private-package

---

bcpkix/1.68.0.wso2v1/pom.xml
commons-io/2.7.0.wso2v1/pom.xml
solr/5.5.5.wso2v2/pom.xml

Related issues wso2/product-is#12485
- bcpkix-jdk15on - 1.68.0.wso2v1
- coomons-io - 2.7.0.wso2v1
- solr - 5.5.5.wso2v2
solr release is done to increase range of common-io.

Release new dependency versions for commons-io, solr, bcpkix-jdk15on.

---

tomcat-catalina-ha/9.0.53.wso2v1/pom.xml
tomcat-el-api/9.0.53.wso2v1/pom.xml
tomcat-jsp-api/9.0.53.wso2v1/pom.xml
tomcat-servlet-api/9.0.53.wso2v1/pom.xml
tomcat-websocket/9.0.53.wso2v1/pom.xml
tomcat/9.0.53.wso2v1/pom.xml
tomcat/9.0.53.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Create tomcat 9.0.53 orbit bundles

---

bcpkix/1.60.0.wso2v1/pom.xml
bcprov/1.60.0.wso2v1/pom.xml

Update bcprov & bcpkix 1.60.0.wso2v1 version to 1.68

---

bcpkix/1.60.0.wso2v1/pom.xml
bcprov/1.60.0.wso2v1/pom.xml

Revert "Update bcprov & bcpkix 1.60.0.wso2v1 version to 1.68"

---

bcpkix/1.60.0.wso2v1/pom.xml
bcprov/1.60.0.wso2v1/pom.xml

$subject
https://github.com/wso2/orbit/pull/506

Update bcprov and bcpkix 1.60.0.wso2v1 versions to 1.66

---

pom.xml
tomcat-catalina-ha/9.0.54.wso2v1/pom.xml
tomcat-el-api/9.0.54.wso2v1/pom.xml
tomcat-jsp-api/9.0.54.wso2v1/pom.xml
tomcat-servlet-api/9.0.54.wso2v1/pom.xml
tomcat-websocket/9.0.54.wso2v1/pom.xml
tomcat/9.0.54.wso2v1/pom.xml
tomcat/9.0.54.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.54 orbit bundles

---

asn-one/0.6.0.wso2v1/pom.xml
bcpkix/1.69.0.wso2v1/pom.xml
bcprov/1.69.0.wso2v1/pom.xml
smbj/0.11.3.wso2v1/pom.xml

> Add SMB 3.0 support and required dependencies.
Related to wso2/micro-integrator/issues/2421

Add SMBJ 0.11.3 and dependencies.

---

xmlbeans/3.1.0.wso2v1/pom.xml

Add xmlbeans orbit 3.1.0

---

jsr105/1.0.1.wso2v1/pom.xml
pom.xml

$Subject
jsr105 is a runtime dependency for xmlsec 2.1.7

Add jsr105 as an orbit bundle

---

opensaml/3.3.1.wso2v2/pom.xml

Change upper bound of xml.security.version range

---

opensaml/3.3.1.wso2v2/pom.xml

Revert "Change upper bound of xml.security.version range"

---

h2/2.0.206.wso2v1/pom.xml
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2ConsoleServiceActivator.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2/2.0.206.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

This PR adds the orbit bundle for H2 v2.0.206 as `2.0.206.wso2v1`.

Add orbit bundle for h2 2.0.206wso2v1

---

jsonpath/2.6.0.wso2v1/pom.xml

> Add jayway 2.6.0 orbit bundle.

Add jayway 2.6.0 orbit bundle.

---

graphQL/17.3-wso2v1/pom.xml

Adding Graphql 17.3-wso2v1

---

yubico-webauthn/1.12.1.wso2v1/pom.xml

Related PR: https://github.com/wso2/orbit/pull/550

Fix dependency issue

---

nimbus/9.18.0.wso2v1/pom.xml

> Updates the nimbus-jose-jwt version to 9.18.
> Addresses the issue - https://github.com/wso2-enterprise/choreo/issues/7940

Add nimbus 9.18.0.wso2v1

---

awslambda/1.11.1034.wso2v1/pom.xml

This PR adds AWS lambda SDK version 1.11.1034 to add support to Cape town region.

Add AWS lambda SDK 1.11.1034

---

bcpkix/1.70.0.wso2v1/pom.xml
bcprov/1.70.0.wso2v1/pom.xml
pom.xml

Add bcprov and bcpkix 1.70.0.wso2v1 modules

---

commons-io/2.11.0.wso2v1/pom.xml
pom.xml
solr/5.5.5.wso2v3/pom.xml

Note $subject and add solr 5.5.5.wso2v3 with commons-io version range change

Add commons-io 2.11.0.wso2v1 module

---

pom.xml

> Add xmlbeans 3.1.0.wso2v1 as a module for parent pom.

Add xmlbeans 3.1.0

---

xmlbeans/3.1.0.wso2v1/pom.xml

Add distributionManagement configs for xmlbeans 3.1.0

---

pom.xml
tomcat-catalina-ha/9.0.58.wso2v1/pom.xml
tomcat-el-api/9.0.58.wso2v1/pom.xml
tomcat-jsp-api/9.0.58.wso2v1/pom.xml
tomcat-servlet-api/9.0.58.wso2v1/pom.xml
tomcat-websocket/9.0.58.wso2v1/pom.xml
tomcat/9.0.58.wso2v1/pom.xml
tomcat/9.0.58.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

* Added the tomcat 9.0.58 orbit bundle
* https://github.com/wso2/orbit/pull/508/commits/c56d14a4d73cee552939353a07e123732e660bfc

Add tomcat 9.0.58 orbit bundle

---

zookeeper/3.7.0.wso2v1/pom.xml

Adding zookeeper 3.7.0

---

tomcat-catalina-ha/9.0.58.wso2v1/pom.xml
tomcat-el-api/9.0.58.wso2v1/pom.xml
tomcat-jsp-api/9.0.58.wso2v1/pom.xml
tomcat-servlet-api/9.0.58.wso2v1/pom.xml
tomcat-websocket/9.0.58.wso2v1/pom.xml
tomcat/9.0.58.wso2v1/pom.xml

* $subject
* https://github.com/wso2/orbit/pull/566
* https://github.com/wso2/orbit/pull/510/commits/e3dfb09686d99acebccb74ccdc5d79caffbdba3c

Change repo URLs to https in pom.xml files of tomcat 9.0.58 bundle

---

openjpa-all/3.0.0.wso2v1/pom.xml
pom.xml

Resolves: https://github.com/wso2/product-is/issues/13042

Add openjpa-all 3.0.0

---

httpcore/4.4.15-wso2v1/pom.xml
pom.xml
xerces/2.12.2.wso2v1/pom.xml

Add xerces-2.12.2.wso2v1 and httpcore-4.4.15-wso2v1 modules

---

pom.xml
velocity/2.3.0.wso2v1/pom.xml

Add the log4j1 removed version of velocity library.

Velocity 2.3.0

---

swagger-parser/1.0.57.wso2v1/pom.xml
swagger-parser/2.0.29.wso2v1/pom.xml

Adds new orbit bundles for swagger-parser `1.0.57.wso2v1` and swagger-parser-3 `2.0.29.wso2v1`.

Add new orbit bundles for swagger-parser

---

swagger-parser/2.0.30.wso2v1/pom.xml

Add swagger-parser 2.0.30

---

swagger-parser/2.0.30.wso2v1/pom.xml

Fix version changes

---

webharvest/2.0.0.wso2v5/pom.xml

Add 2.0.0.wso2v5

---

tiles/2.0.5.wso2v2/pom.xml

Part of https://github.com/wso2/orbit/pull/564

Update tiles-jsp 2.0.5.wso2v2 pom

---

jdbc-pool/9.0.58.wso2v1/pom.xml

This PR adds the orbit bundle jdbc-pool `9.0.58.wso2v1`.

Add orbit bundle for tomcat jdbc-pool 9.0.58

---

httpcore-nio/4.4.15.wso2v1/pom.xml

Add httpcore-nio 4.4.15

---

olingo-server/4.8.0wso2v1/pom.xml

$subject (Upgrading commons-io usages)

Add olingo-server 4.8.0

---

olingo-server/4.4.0wso2v3/pom.xml

$subject (Increasing the commons-io version range)

Add olingo-server 4.4.0wso2v3

---

groovy/2.4.8.wso2v1/pom.xml
pom.xml

$subject
backport - https://github.com/wso2-support/orbit/pull/268

Add Groovy to Orbit

---

pom.xml
solr/8.11.1.wso2v2/pom.xml
solr/8.11.1.wso2v3/pom.xml

- Embed zookeepr jar along with solr orbit bundle
- Embed github caffeine jar to fix carbon registry issues after solr version 8 upgrade.

Add Solr 8.11.1.wso2v3

---

solr/8.11.1.wso2v3/pom.xml

Fix solr 8.11.1.wso2v3 version issue

---

groovy/2.4.8.wso2v2/pom.xml
pom.xml

Add groovy 2.4.8.wso2v2

---

spring-framework/5.3.14.wso2v1/pom.xml

Reformated spring 5.3.14.wso2v1

---

hazelcast/3.12.2.wso2v2/pom.xml
pom.xml

Removed log4j1 import statement from bundle. 
https://github.com/wso2/orbit/blob/master/hazelcast/3.12.2.wso2v1/pom.xml#L60

Add hazelcast 3.12.2.wso2v2

---

webauthn4j/0.19.1.wso2v1/pom.xml

Update group id of the webauthn4j orbit

---

libthrift/0.16.0.wso2v1/pom.xml
pom.xml

Add libthrift 0.16.0.wso2v1

---

quartz/2.3.2.wso2v1/pom.xml

Update groupId for quartz 2.3.2

---

nimbus/9.22.0.wso2v1/pom.xml

Add nimbus 9.22.0.wso2v1

---

geronimo-kernel/3.0.1.wso2v1/pom.xml

Fix issue in geronimo kernel bundle

---

openjdk-nashorn/15.3.wso2v1/pom.xml
pom.xml

Add Openjdk/nasshron to orbit

---

opensaml/2.6.6.wso2v5/pom.xml
pom.xml

> Upgrade xmlsec to 2.1.7. 
> Remove log4j and embed reload4j.

Add opensaml-2.6.6.wso2v5 with xmlsec upgrade and reload4j embedded

---

pom.xml

Adding modules to the pom.xml

---

js/1.7.14.wso2v1/pom.xml

Add rhino 1.7.14.wso2v1

---

commons-dbcp2/2.9.0.wso2v1/pom.xml

Add distributionManagement for Apache Commons DBCP 2.9.0.wso2v1

---

hazelcast/4.2.5.wso2v1/pom.xml
pom.xml

Add Hazelcast 4.2.5.wso2v1

---

jstl/1.2.1.wso2v3/pom.xml

Add missing distribution management to jstl bundle

---

opentelemetry-all/0.11.0.wso2v2/pom.xml

added 0.11.0.wso2v2 bundle

---

pom.xml

Adding solr_8.11.1.wso2v4 module to the parent pom. Part of https://github.com/wso2/orbit/pull/694
> Link to the PR for changes …

Add solr_8.11.1.wso2v4 module to the parent pom

---

awslambda/1.11.1034.wso2v2/pom.xml

This PR adds sts dependency to this custom bundle that wraps aws-java-sdk-core/lambda.

Add awslambda v2 with sts dependency

---

graphQL/18.2-wso2v1/pom.xml

Upgrade the graphql-java version to `18.2`.

Add graphql 18.2-wso2v1

---

opentelemetry-all/0.11.0.wso2v3/pom.xml

Added 0.11.0.wso2v3 bundle

---

pom.xml

> $Subject
Relates to PR https://github.com/wso2/orbit/pull/773
Relates to issue https://github.com/wso2/product-is/issues/14289

Add solr_8.11.1.wso2v5 module to the parent pom

---

reflections/0.9.11.wso2v1/pom.xml

Change version range for com.google.common package due to guava version upgrade

---

nimbus/7.9.0.wso2v1/pom.xml

Add Nimbus 7.9

---

snakeyaml/1.31.0.wso2v1/pom.xml

Add snakeyaml 1.31.0.wso2v1

---

snakeyaml/1.32.0.wso2v1/pom.xml

Add snakeyaml 1.32.0.wso2v1

---

jdbc-pool/9.0.65.wso2v1/pom.xml
pom.xml

$subject
relates to: [#313](https://github.com/wso2-support/orbit/pull/313)

Add jdbc-pool-9.0.65.wso2v1

---

snakeyaml/1.33.0.wso2v1/pom.xml

$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Add snakeyaml 1.33.0.wso2v1

---

pom.xml
smooks/1.5.1.wso2v5/pom.xml

relates to: https://github.com/wso2/api-manager/issues/545

Add smooks/1.5.1.wso2v5 with Freemarker 2.3.31

---

azure-messaging-servicebus-sdk-all/7.11.0.wso2v1/pom.xml

https://github.com/wso2-enterprise/choreo/issues/14965 …

Change asb sdk version

---

activation/1.1.1.wso2v4/pom.xml
quartz/2.3.0.wso2v3/pom.xml
reflections/0.9.11.wso2v2/pom.xml

> Add the following oribt bundles:
- quartz 2.3.0.wso2v3
- activation 1.1.1.wso2v4
- reflections 0.9.11.wso2v2

Add quartz 2.3.0.wso2v3, activation 1.1.1.wso2v4, and reflections 0.9.11.wso2v2

---

ant/1.10.12.wso2v1/pom.xml
poi-scratchpad/5.2.3.wso2v1/pom.xml

- Add new Ant core orbit bundle
- Add Apache poi-scratchpad bundle
- Update the ant core and poi-scratchpad versions

Add Ant and Apache poi-scratchpad new versions

---

poi-scratchpad/5.2.3.wso2v1/pom.xml

- Updated the import and export configurations in poi-scratchpad 5.2.3 bundle
- Source : https://github.com/wso2/orbit/blob/master/poi-scratchpad/3.17.0.wso2v1/pom.xml#L53

Update poi-scratchpad 5.2.3 orbit bundle

---

commons-text/1.10.0.wso2v1/pom.xml

This PR adds a new orbit bundle for commons-text.

Add commons-text 1.10.0

---

commons-lang/3.12.0.wso2v1/pom.xml
commons-text/1.10.0.wso2v2/pom.xml

Add commons-lang 3.12.0

---

solr/8.11.1.wso2v6/pom.xml

> Fix PR comments in https://github.com/wso2/orbit/pull/781

Fix PR comments

---

azure-qpid-proton-j-extensions/1.2.4.wso2v1/pom.xml

Add azure qpid bundle
Add azure qpid bundle
> Type “Sent” when you have provided new/updated certification questions, plus …

Add azure qpid bundle

---

graphQL/19.2-wso2v1/pom.xml

Adding graphql 19.2

---

httpcore-nio/4.4.16-wso2v1/pom.xml
httpcore/4.4.16-wso2v1/pom.xml

Adds the following orbit bundles.
- httpcore-4.4.16.wso2v1
- httpcore-nio-4.4.16.wso2v1

Adds orbit bundles for httpcore-4.4.16 and httpcore-nio-4.4.16

---

hazelcast/4.2.6.wso2v1/pom.xml

Add Hazelcast 4.2.6.wso2v1

---

pom.xml

add Hazelcast 4.2.6.wso2v1 module

---

graphQL/19.2-wso2v2/pom.xml

Adding graphql 19.2-wso2v2 with i18n

---

tomcat-catalina-ha/9.0.70.wso2v1/pom.xml
tomcat-el-api/9.0.70.wso2v1/pom.xml
tomcat-jsp-api/9.0.70.wso2v1/pom.xml
tomcat-servlet-api/9.0.70.wso2v1/pom.xml
tomcat/9.0.70.wso2v1/pom.xml
tomcat/9.0.70.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

> $subject. The following are added:
- `tomcat-9.0.70.wso2v1.jar`
- `tomcat-catalina-ha-9.0.70.wso2v1.jar`
- `tomcat-el-api-9.0.70.wso2v1.jar`
- `tomcat-jsp-api-9.0.70.wso2v1.jar`
- `tomcat-servlet-api-9.0.70.wso2v1.jar`

Add tomcat 9.0.70.wso2v1 bundles

---

swagger-parser/2.1.10.wso2v1/pom.xml

Add swagger-parser 2.1.10.wso2v1 bundle

---

jackson-databind/2.11.0.wso2v1/pom.xml
kafka-avro-serializer/7.3.1.wso2v1/pom.xml
kafka-schema-registry-client/7.3.1.wso2v1/pom.xml

Fix import export issue for jackson databind due to newly added package

---

jackson-databind/2.11.0.wso2v1/pom.xml
kafka-avro-serializer/7.3.1.wso2v1/pom.xml
kafka-schema-registry-client/7.3.1.wso2v1/pom.xml

Revert "Fix import export issue for jackson databind due to newly added package"

---

jackson-databind/2.11.0.wso2v2/pom.xml

Fix import export for exc package

Fix import export issue for exc package in jackson databind

---

okhttp/4.9.3.wso2v2/pom.xml
okio/2.8.0.wso2v2/pom.xml

Upgrades kotlin-stdlib version used in okhttp and okio from 1.4.10 to 1.8.0.
Related git issue: https://github.com/wso2/api-manager/issues/1225
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …

Upgrade kotlin-stdlib versions in okhttp and okio

---

json-simple/1.1.1.wso2v1/pom.xml

Adds orbit bundle for json-simple
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

Add orbit bundle for json-simple

---

tomcat-catalina-ha/9.0.71.wso2v1/pom.xml
tomcat-el-api/9.0.71.wso2v1/pom.xml
tomcat-jsp-api/9.0.71.wso2v1/pom.xml
tomcat-servlet-api/9.0.71.wso2v1/pom.xml
tomcat/9.0.71.wso2v1/pom.xml
tomcat/9.0.71.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Bump Tomcat orbit versions to 9.0.71

---

json-simple/1.1.1.wso2v1/pom.xml

Add distributionManagement section to json-simple pom

---

jettison/1.5.3.wso2v1/pom.xml

Adds jettison 1.5.3
Related git issue : https://github.com/wso2/api-manager/issues/1342
> Link to the PR for changes to the …

Add jettison 1.5.3

---

js/1.7.13.wso2v1/pom.xml

Add rhino 1.7.13.wso2v1

---

ant/1.10.13.wso2v1/pom.xml

add new ant version

---

reflections/0.9.11.wso2v3/pom.xml

> This PR will update gson import range to 2.2 - 3.0 in order to bump Gson versions on MSF4J repo

Update org.reflections gson import range

---

ua-parser/1.5.2.wso2v2/pom.xml

Update Snakeyaml version to 1.33 in ua-parser

---

h2/2.1.214.wso2v1/pom.xml
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2ConsoleServiceActivator.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2/2.1.214.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

added  h2 2.1.214.wso2v1

---

jdbc-pool/9.0.71.wso2v1/pom.xml

Bump tomcat JDBC version to 9.0.71 in jdbc-pool jar

---

handlebars/4.0.7.wso2v1/pom.xml
handlebars/4.3.1.wso2v1/pom.xml

> Add handlebars 4.3.1 orbit bundle

Add handlebars 4.3.1 orbit bundle

---

okhttp/4.2.0.wso2v2/pom.xml
okio/2.4.0.wso2v2/pom.xml

This PR updates Kotlin to 1.8.10 for APIM 4.0

Okio 2.4.0.wso2v2 and Okhttp 4.2.0.wso2v2

---

olingo-server/4.9.0wso2v1/pom.xml

Add OData Server 4.9.0.wso2v1

---

yubico-webauthn/2.4.0-RC2.wso2v1/pom.xml

Add yubico-webauthn 2.4.0-RC2.wso2v1

---

yubico-webauthn/2.4.0.wso2v1/pom.xml

Add yubico-webauthn 2.4.0.wso2v1

---

libthrift/0.14.0.wso2v1/pom.xml

This is to upgrade Libthrift to 0.14.0.

Upgrading Libthrift to 0.14.0

---

commons-fileupload/1.5.0.wso2v1/pom.xml

Adding commons-fileupload latest version 1.5[1] 
[1] [https://mvnrepository.com/artifact/commons-fileupload/commons-fileupload/1.5](https://mvnrepository.com/artifact/commons-fileupload/commons-fileupload/1.5)

Add commons-fileupload 1.5.0.wso2v1

---

swagger-codegen/2.3.1.wso2v3/pom.xml

Adds plexus utils v3.3.1

---

swagger-codegen/2.4.21.wso2v1/pom.xml

This is to fix the issue on APIM 4.0.0

Upgrading swagger-codegen to 2.4.21

---

commons-fileupload/1.5.0.wso2v2/pom.xml

This PR fixes commons.io and commons.io.output version to 2.2

Fixes commons.io and commons.io.output version to 2.2

---

swagger-codegen/2.4.21.wso2v2/pom.xml

This is to avoid any patch conflicts

Upgrade plexus.utils.version in Swagger Codegen

---

snakeyaml/2.0.0.wso2v1/pom.xml

Add snakeyaml 2.0.0.wso2v1

---

protobuf-java/3.22.2.wso2v1/pom.xml

This PR creates `protobuf-java 3.22.2.wso2v1 bundle`.

Create protobuf-java 3.22.2.wso2v1 bundle

---

tomcat-catalina-ha/9.0.73.wso2v1/pom.xml
tomcat-el-api/9.0.73.wso2v1/pom.xml
tomcat-jsp-api/9.0.73.wso2v1/pom.xml
tomcat-servlet-api/9.0.73.wso2v1/pom.xml
tomcat/9.0.73.wso2v1/pom.xml
tomcat/9.0.73.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

> $subject. The following are added.
- tomcat-9.0.73.wso2v1.jar
- tomcat-catalina-ha-9.0.73.wso2v1.jar
- tomcat-el-api-9.0.73.wso2v1.jar
- tomcat-jsp-api-9.0.73.wso2v1.jar
- tomcat-servlet-api-9.0.73.wso2v1.jar

Add tomcat 9.0.73.wso2v1 bundles

---

tomcat-catalina-ha/9.0.74.wso2v1/pom.xml
tomcat-el-api/9.0.74.wso2v1/pom.xml
tomcat-jsp-api/9.0.74.wso2v1/pom.xml
tomcat-servlet-api/9.0.74.wso2v1/pom.xml
tomcat/9.0.74.wso2v1/pom.xml
tomcat/9.0.74.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

> $subject. The following are added.
- tomcat-9.0.74.wso2v1.jar
- tomcat-catalina-ha-9.0.74.wso2v1.jar
- tomcat-el-api-9.0.74.wso2v1.jar
- tomcat-jsp-api-9.0.74.wso2v1.jar
- tomcat-servlet-api-9.0.74.wso2v1.jar

Add tomcat 9.0.74.wso2v1 bundles

---

hazelcast/3.12.13.wso2v1/pom.xml

> Add hazelcast version 3.12.13

Add hazelcast 3.12.13

---

pom.xml
webauthn4j/0.21.0.wso2v1/pom.xml

Add webauthn4j v0.21.0.RELEASE bundle

---

swagger-parser/1.0.65.wso2v1/pom.xml

Update swagger-parser export range

Update swagger-parser export range

---

jsonpath/2.4.0.wso2v3/pom.xml

To release JsonPath 2.4.0 with Json-smart 2.4.7

JsonPath 2.4.0.wso2v3

---

pom.xml

> Add spring-framework 5.3.27.wso2v1 to root pom

Add spring-framework 5.3.27.wso2v1 to root pom

---

json/3.0.0.wso2v2/pom.xml

Adding json_3.0.0.wso2v2

---

httpclient5/5.2.1.wso2v1/pom.xml
httpcore5/5.2.1.wso2v1/pom.xml
pom.xml

Adding orbit bundles for Apache core and client v5.
- https://mvnrepository.com/artifact/org.apache.httpcomponents.core5/httpcore5/5.2.1
- https://mvnrepository.com/artifact/org.apache.httpcomponents.core5/httpcore5-h2/5.2.1
- https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5/5.2.1
> Brief description of the new feature or bug fix as it will …

Add orbit bundles for http core and client v5

---

jettison/1.5.4.wso2v1/pom.xml

Add Jettison 1.5.4.wso2v1

---

kafka-schema-registry-client/7.3.1.wso2v2/pom.xml

Fix https://github.com/wso2/api-manager/issues/1922 …

Add maven services for kafka-schema-registry-client-7.3.1 wso2 jar

---

xalan/2.7.3.wso2v1/pom.xml

Add xalan 2.7.3.wso2v1

---

tomcat-catalina-ha/9.0.76.wso2v1/pom.xml
tomcat-el-api/9.0.76.wso2v1/pom.xml
tomcat-jsp-api/9.0.76.wso2v1/pom.xml
tomcat-servlet-api/9.0.76.wso2v1/pom.xml
tomcat/9.0.76.wso2v1/pom.xml
tomcat/9.0.76.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.76 components.
1. tomcat
2. tomcat-catalina-ha
3. tomcat-el-api
4. tomcat-jsp-api
5. tomcat-servlet-api

Add tomcat 9.0.76

---

bcel/6.7.0.wso2v1/pom.xml
commons-codec/1.16.0.wso2v1/pom.xml

Add commons-codec 1.16.0.wso2v1 and bcel 6.7.0.wso2v1

---

serializer/2.7.3.wso2v1/pom.xml

Add xalan serializer 2.7.3.wso2v1

---

swagger-core/1.6.9.wso2v1/pom.xml

This PR adds swagger-core v1.6.9 as a orbit bundle.

Add swagger-core orbit bundle

---

yubico-webauthn/1.10.1.wso2v3/pom.xml
yubico-webauthn/1.12.1.wso2v2/pom.xml
yubico-webauthn/1.3.0.wso2v6/pom.xml

> Support [Guava: Google Core Libraries For Java](https://mvnrepository.com/artifact/com.google.guava/guava) versions range up to 34.0.0.

Add  yubico-webauthn 1.3.0.wso2v6, 1.10.1.wso2v3, 1.12.1.wso2v2

---

jdbc-pool/9.0.76.wso2v1/pom.xml
pom.xml

Add jdbc-pool 9.0.76.wso2v1

---

h2-engine/2.2.220.wso2v1/pom.xml
h2-engine/2.2.220.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2DatabaseServiceActivator.java
h2-engine/2.2.220.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/database/H2DatabaseManager.java
h2-engine/2.2.220.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
pom.xml

Add h2database 2.2.220.wso2v1

---

cdc-mi/1.0.0wso2v1/pom.xml
debezium/2.1.4.Final.wso2v1/pom.xml

> Contains Debezium, Kafka and binlog connector dependencies.

Introduce new orbit bundle for cdc inbound endpoint in MI.

---

ua-parser/1.5.4.wso2v2/pom.xml

This bundle represents ua-parser 1.5.4 and the default snakeyaml version is replaced by version 2.0

Add ua-parser 1.5.4.wso2v2

---

pom.xml
solr/8.11.1.wso2v8/pom.xml

$subject
we are excluding the `org.apache.hadoop:hadoop-common:3.2.2` dependency that is packed from the solr-core and packing the version 3.2.4 instead

Add solr 8.11.1.wso2v8

---

ant/1.10.14.wso2v1/pom.xml

This PR adds Apache Ant Core v1.10.14.wso2v1.

Add Apache Ant Core v1.10.14.wso2v1

---

opentelemetry-all/1.11.0.wso2v5/pom.xml

Changing guava dependency range

Change guava dependency version range to support 32.x

---

commons-io/2.13.0.wso2v1/pom.xml

Add commons-io 2.13.0.wso2v1

---

ua-parser/1.5.4.wso2v3/pom.xml

Upgrading the snake-yaml version to v2.2.0 in ua-parser v1.5.4

Add ua-parser 1.5.4.wso2v3

---

tomcat-catalina-ha/9.0.80.wso2v1/pom.xml
tomcat-el-api/9.0.80.wso2v1/pom.xml
tomcat-jsp-api/9.0.80.wso2v1/pom.xml
tomcat-servlet-api/9.0.80.wso2v1/pom.xml
tomcat/9.0.80.wso2v1/pom.xml
tomcat/9.0.80.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.80

---

netty/4.1.98.wso2v1/pom.xml

Add netty-all 4.1.98.wso2v1

---

zipkin-sender-okhttp3/2.16.4.wso2v2/pom.xml

Add zipkin-sender-okhttp3 2.16.4.wso2v2

---

httpclient/4.5.14.wso2v1/pom.xml

Add httpclient 4.5.14.wso2v1

---

json-schema-validator-all/2.2.6.wso2v9/pom.xml

$subject
Upgrading the com.google.common.imp pkg version range

Add new orbit bundle for json-schema-validator-all

---

tomcat-catalina-ha/9.0.81.wso2v1/pom.xml
tomcat-el-api/9.0.81.wso2v1/pom.xml
tomcat-jsp-api/9.0.81.wso2v1/pom.xml
tomcat-servlet-api/9.0.81.wso2v1/pom.xml
tomcat/9.0.81.wso2v1/pom.xml
tomcat/9.0.81.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.81

---

activiti-all/5.23.0.wso2v2/pom.xml

$subject
Upgrading the org.apache.commons.io.import.range

Add new orbit bundle for activiti-all

---

batik/1.17.0.wso2v1/pom.xml

Add batik 1.17.0.wso2v1

---

tomcat-catalina-ha/9.0.82.wso2v1/pom.xml
tomcat-el-api/9.0.82.wso2v1/pom.xml
tomcat-jsp-api/9.0.82.wso2v1/pom.xml
tomcat-servlet-api/9.0.82.wso2v1/pom.xml
tomcat/9.0.82.wso2v1/pom.xml
tomcat/9.0.82.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.82

---

tomcat-catalina-ha/9.0.82.wso2v1/pom.xml
tomcat-el-api/9.0.82.wso2v1/pom.xml
tomcat-jsp-api/9.0.82.wso2v1/pom.xml
tomcat-servlet-api/9.0.82.wso2v1/pom.xml
tomcat/9.0.82.wso2v1/pom.xml
tomcat/9.0.82.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

$subject (Also avoided packing json-smart and asm jars within the bundle)

Add json-path 2.7.0.wso2v1

---

hazelcast/5.3.2.wso2v1/pom.xml
pom.xml

> Add hazelcast 5.3.2 and move to Hazelcast Platform product (hazelcast) from Hazelcast IMDG (hazelcast-all).

Add hazelcast 5.3.2

---

bcprov/1.74.0.wso2v1/pom.xml
pom.xml

Add bcprov 1.74.0.wso2v1

---

pom.xml
solr/8.11.1.wso2v9/pom.xml

Upgrade jetty version in solr

---

guava/32.1.3.wso2v1/pom.xml
pom.xml

Add guava 32.1.3.wso2v1

---

json/3.0.0.wso2v3/pom.xml

> $subject
> Adding 20230227 orbit bundle

Add json 3.0.0.wso2v3 

---

commons-compress/1.22.0.wso2v1/pom.xml
poi/5.2.3.wso2v1/pom.xml
xmlbeans/5.1.1.wso2v1/pom.xml

Fix license header

---

azure-core-amqp/2.8.9.wso2v1/pom.xml
azure-core/1.43.0.wso2v1/pom.xml
azure-messaging-eventhubs/5.16.0.wso2v1/pom.xml
pom.xml
reactor-core/3.4.31.wso2v1/pom.xml

Fix for issue https://github.com/wso2/api-manager/issues/2254

azure and reactor version bump

---

opencensus/0.31.1.wso2v2/pom.xml
swagger-parser/2.1.18.wso2v1/pom.xml

> Change the guava import version range in opencesus Add a new swagger-parser version

Add new orbit bundles opencensus and swagger parser

---

pom.xml
solr/8.11.1.wso2v10/pom.xml

Upgrades the zookeeper version.

Add solr 8.11.1.wso2v10

---

openapi-generator/4.3.1.wso2v7/pom.xml

Bump slf4j from 1.7.12 to 1.7.36 and add v6 changes

Slf4j Bump

---

openapi-generator/4.3.1.wso2v7/pom.xml

Add corrections from v2 to v7
```diff
...		
Javascript-Flowtyped;version="${export.pkg.version.swagger-codegen}",
Javascript.es6;version="${export.pkg.version.swagger-codegen}",
+      Javascript.libraries.javascript;version="${export.pkg.version.swagger-codegen}",
...
python-blueplanet.*;version="${export.pkg.version.swagger-codegen}",
python-flask;version="${export.pkg.version.swagger-codegen}",
+          python-prior.*;version="${export.pkg.version.swagger-codegen}",
...
<_exportcontents>
com.github.jknack.handlebars,
-            com.gicommons-iothub.jknack.handlebars.context,
+            com.github.jknack.handlebars.context,
```

Add corrections from v2

---

json/3.0.0.wso2v4/pom.xml

Upgrade json version to 20231013

Add 3.0.0.wso2v4 for json

---

zookeeper/3.9.1.wso2v1/pom.xml

Add relevant maven repositories related to https://github.com/wso2/orbit/pull/1037

Add relevant maven repositories

---

bcpkix/1.74.0.wso2v1/pom.xml

Add bcpkix 1.74.0.wso2v1

---

groovy/3.0.19.wso2v1/pom.xml

Add groovy version 3.0.19

---

bcprov/1.77.0.wso2v1/pom.xml

> Add bcprov-jdk18on 1.77 version

Add bcprov-jdk18on 1.77 version

---

drools/7.74.1-wso2v1/META-INF/drools.default.packagebuilder.conf
drools/7.74.1-wso2v1/META-INF/kie.conf
drools/7.74.1-wso2v1/META-INF/kmodule.xml
drools/7.74.1-wso2v1/pom.xml

Add drools 7.74.1.Final as a orbit bundle

Add drools 7.74.1.Final as a orbit bundle

---

swagger-jaxrs/1.6.9.wso2v1/pom.xml

This PR adds `swagger-jaxrs_1.6.9.wso2v1`

Add swagger-jaxrs 1.6.9.wso2v1 version

---

solr/8.11.1.wso2v11/pom.xml

> Upgrade zookeeper version in solr

Upgrade zookeeper version in solr

---

azure-messaging-servicebus-sdk-all/7.14.6.wso2v1/pom.xml

> $subject
Relevant issue: https://github.com/wso2-enterprise/choreo/issues/25674 …

[do not merge] Update version of azure messaging servicebus sdk to 7.14.6

---

reflections/0.10.2.wso2V2/pom.xml

This PR adds `reflections-0.10.2.wso2v2`

Add reflections 0.10.2.wso2v2

---

solr/8.11.1.wso2v11/pom.xml

> Change the artifact version of the deployed orbit bundle

Change the artifact version

---

reflections/0.9.11.wso2v4/pom.xml
swagger-jaxrs/1.6.9.wso2v2/pom.xml

Add `swagger-jaxrs 1.6.9.wso2v2` and `reflections 0.9.11.wso2v4` bundles

---

swagger-core/1.6.9.wso2v3/pom.xml

Upgrade guava version range

---

json-schema-validator-all/2.2.6.wso2v10/pom.xml

Update com.google.common version range

---

swagger-core/1.6.9.wso2v4/pom.xml

Update com.google.common version range and jackson version

---

ua-parser/1.6.1.wso2v1/pom.xml

Add ua_parser 1.6.1 orbit

---

swagger-core/1.6.11.wso2v1/pom.xml

Fix groupid of swagger core orbit

---

jsonpath/2.9.0.wso2v1/pom.xml

change slf4j version range

---

swagger-parser/2.1.20.wso2v1/pom.xml

Add swagger parser 2.1.20.wso2v1 orbit

Add swagger parser 2.1.20.wso2v1 orbit

---

tomcat-catalina-ha/9.0.85.wso2v1/pom.xml
tomcat-el-api/9.0.85.wso2v1/pom.xml
tomcat-jsp-api/9.0.85.wso2v1/pom.xml
tomcat-servlet-api/9.0.85.wso2v1/pom.xml
tomcat/9.0.85.wso2v1/pom.xml
tomcat/9.0.85.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.85 orbit

---

hazelcast/5.3.6.wso2v1/pom.xml

Add hazelcast-5.3.6.wso2v1

---

okhttp/4.12.0.wso2v1/pom.xml
opentelemetry-all/1.34.1.wso2v1/pom.xml
zipkin-sender-okhttp3/3.3.0.wso2v1/pom.xml

Add okhttp 4.12.0, zipkin sender 3.3 and opentelemetry 1.34.1 changes

---

pom.xml
solr/9.5.0.wso2v1/pom.xml

Release solr 9.5.0.wso2v1

---

opentelemetry-all/1.11.0.wso2v6/pom.xml
zipkin-sender-okhttp3/3.3.0.wso2v1/pom.xml

Add opentelemetry-1.11.0.wso2v6 and fix zipkin-sender-okhttp3

---

nimbus/9.37.3.wso2v1/pom.xml
pom.xml

$subject
Related issue: https://github.com/wso2/api-manager/issues/2526

Add new bundle for nimbus-9.37.3

---

jms-api/2.0.1.wso2v1/pom.xml
pom.xml

> $subject
> This is to facilitate carbon-cache-sync-manager

Add jms-api 2.0.1 orbit bundle

---

solr/9.5.0.wso2v4/pom.xml

This PR adds the dependency solr 9.5.0.wso2v4 with io.opentracing dependencies added as include-resources.
Related issue: https://github.com/wso2/api-manager/issues/2677

Add solr 9.5.0.wso2v4 dependency

---

bcpkix/1.76.0.wso2v1/pom.xml
bcprov/1.76.0.wso2v1/pom.xml

Add bcprov and bcpkix v1.76.0.wso2v1

---

zipkin-sender-okhttp3/2.17.2.wso2v1/pom.xml

$subject
Related to https://github.com/wso2/api-manager/issues/2582

Add zipkin-sender-okhttp3 bundle

---

pom.xml
solr/9.5.0.wso2v5/pom.xml

Release solr 9.5.0.wso2v5

---

h2/2.2.224.wso2v1/pom.xml
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2ConsoleServiceActivator.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2/2.2.224.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

Add new h2 version 2.2.224.wso2v1

---

solr/8.11.1.wso2v12/pom.xml
zookeeper/3.9.2.wso2v1/pom.xml

Address CVE-2024-23944 
For the fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/5945
Zookeeper 3.9.2 added
Solr 8.11.1 zookeeper version upgraded to 3.9.2

Add New Zookeeper and Solr Versions

---

solr/8.11.1.wso2v13/pom.xml

Add new solr version where the http2-common version is bumped from 9.4.53.v20231009 to 9.4.54.v20240208

Add new solr version

---

kafka-avro-serializer/7.6.0.wso2v1/pom.xml
kafka-schema-registry-client/7.6.0.wso2v1/pom.xml
kafka-schema-serializer/7.6.0.wso2v1/pom.xml

Add the following Kafka orbits,
- kafka-avro-serializer
- kafka-schema-registry-client
- kafka-schema-serializer

Add Kafka 7.6.0 orbits

---

pom.xml
spring-framework/5.3.33.wso2v2/pom.xml
spring-framework/5.3.33.wso2v2/src/main/resources/META-INF/spring.factories
spring-framework/5.3.33.wso2v2/src/main/resources/META-INF/spring.handlers
spring-framework/5.3.33.wso2v2/src/main/resources/META-INF/spring.tooling

Adding spring-framework v5.3.33.wso2v2

---

commons-compress/1.26.1.wso2v1/pom.xml

Add new non-vulnerable commons-compress version 1.26.1 to orbit

Add commons-compress version 1.26.1

---

swagger-request-validator/2.12.1.wso2v4/pom.xml

Add swagger-request-validator-core 2.12.1.wso2v4

---

json-schema-validator-all/2.2.7.wso2v2/pom.xml

Add json-schema-validator-2.2.7.wso2v2

---

okio/3.9.0.wso2v1/pom.xml

Add okio 3.9.0.wso2v1 orbit bundle

---

tomcat-catalina-ha/9.0.88.wso2v1/pom.xml
tomcat-el-api/9.0.88.wso2v1/pom.xml
tomcat-jsp-api/9.0.88.wso2v1/pom.xml
tomcat-servlet-api/9.0.88.wso2v1/pom.xml
tomcat/9.0.88.wso2v1/pom.xml
tomcat/9.0.88.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

- fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6143

Bump: Tomcat version to 9.0.88

---

hazelcast/5.4.0.wso2v1/pom.xml

Add hazelcast 5.4.0.wso2v1

---

hazelcast/5.3.7.wso2v1/pom.xml

Add hazelcast 5.3.7.wso2v1

---

mime4j-core/0.8.11.wso2v1/pom.xml

Add apache-mime4j-core 0.8.11.wso2v1

---

solr/9.5.0.wso2v6/pom.xml

- Additionally pack java assist library

Add Solr 9.5.0.wso2v6

---

okhttp/4.9.3.wso2v4/pom.xml

Add okhttp 4.9.3.wso2v4 bundle with new okio version range

---

json/3.0.0.wso2v5/pom.xml

Release json-20240303 from orbit

---

commons-codec/1.17.0.wso2v1/pom.xml

Release commons-codec-1.17.0 from orbit

---

jstl/1.2.1.wso2v4/pom.xml
jstl/1.2.2.wso2v2/pom.xml

Release jstl 1.2.1.wso2v4 and 1.2.2.wso2v2 versions

---

opensaml/2.6.6.wso2v7/pom.xml

Add Opensaml v2.6.6.wso2v7

---

h2-engine/2.3.232.wso2v1/pom.xml
h2-engine/2.3.232.wso2v1/src/main/java/org/console/ConsoleService.java
h2-engine/2.3.232.wso2v1/src/main/java/org/console/H2DatabaseManager.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/H2DatabaseServiceActivator.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/database/H2DatabaseManager.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2-engine/2.3.232.wso2v1/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java
pom.xml

Add H2 orbit bundle for 2.3.232

---

tomcat-catalina-ha/9.0.94.wso2v1/pom.xml
tomcat-el-api/9.0.94.wso2v1/pom.xml
tomcat-jsp-api/9.0.94.wso2v1/pom.xml
tomcat-servlet-api/9.0.94.wso2v1/pom.xml
tomcat/9.0.94.wso2v1/pom.xml
tomcat/9.0.94.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

To add the following tomcat 9.0.94.wso2v1 bundles.
- `tomcat-9.0.94.wso2v1.jar`
- `tomcat-catalina-ha-9.0.94.wso2v1.jar`
- `tomcat-el-api-9.0.94.wso2v1.jar`
- `tomcat-jsp-api-9.0.94.wso2v1.jar`
- `tomcat-servlet-api-9.0.94.wso2v1.jar`

Add tomcat 9.0.94.wso2v1 bundles

---

swagger-parser/2.1.22.wso2v1/pom.xml

To add the swagger-parser 2.1.22.wso2v1 bundles.

Add swagger-parser 2.1.22.wso2v1 bundles

---

poi-ooxml/5.3.0.wso2v1/pom.xml
poi/5.3.0.wso2v1/pom.xml

This PR adds the following bundles.
- poi-5.3.0.wso2v1
- poi-ooxml-5.3.0.wso2v1

Add poi v5.3.0.wso2v1 bundle

---

solr/9.5.0.wso2v7/pom.xml

> Upgrade calcite-core version to `1.37.0
Related issue: https://github.com/wso2/product-is/issues/21200`
> Link to the PR for …

Add Solr 9.5.0.wso2v7

---

swagger-parser/2.1.22.wso2v2/pom.xml

To add the swagger-parser 2.1.22.wso2v2 bundles.

Add swagger-parser 2.1.22.wso2v2 bundles

---

graphQL/19.11-wso2v1/pom.xml

Add graphQL version 19.11

---

solr/8.11.1.wso2v14/pom.xml

To add solr 8.11.1.wso2v14 with commons-io version upgrade.

Add solr 8.11.1.wso2v14 with commons-io version upgrade

---

swagger-parser/2.0.30.wso2v2/pom.xml

Add `swagger-parser 2.0.30.wso2v2` bundle. This `apache-commons-io` version is updated to `2.17.0`

Add swagger-parser 2.0.30.wso2v2 bundle

---

commons-lang/3.17.0.wso2v1/pom.xml

Add commons-lang3 3.17.0 bundle

---

swagger-parser/2.1.18.wso2v3/pom.xml

Add swagger parser 2.1.18.wso2v3 bundle

---

poi-scratchpad/5.3.0.wso2v1/pom.xml

Add poi-scratch-pad 5.3.0.wso2v1

---

ant/1.10.15.wso2v1/pom.xml
xmlbeans/5.2.2.wso2v1/pom.xml

Bump Apache Ant and XMLBeans versions

---

hapi/2.1.0.wso2v1/pom.xml
hapi/2.4.0.wso2v1/pom.xml
pom.xml

Add Hapi HL7 orbit lib

---

hapi/2.1.0.wso2v1/pom.xml
hapi/2.4.0.wso2v1/pom.xml

Adding mvn repositories to hapi libs

---

hapi/2.1.0.wso2v1/pom.xml
hapi/2.4.0.wso2v1/pom.xml

Fix issue with resolving hapi dependencies

---

hapi/2.4.0.wso2v2/pom.xml
pom.xml

Add hapi 2.4 orbit lib v2

---

pom.xml
tomcat-catalina-ha/9.0.98.wso2v1/pom.xml
tomcat-el-api/9.0.98.wso2v1/pom.xml
tomcat-jsp-api/9.0.98.wso2v1/pom.xml
tomcat-servlet-api/9.0.98.wso2v1/pom.xml
tomcat/9.0.98.wso2v1/pom.xml
tomcat/9.0.98.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Adds the following tomcat bundles.
- tomcat/9.0.98.wso2v1
- tomcat-catalina-ha/9.0.98.wso2v1
- tomcat-el-api/9.0.98.wso2v1
- tomcat-jsp-api/9.0.98.wso2v1
- tomcat-servlet-api/9.0.98.wso2v1

Add tomcat 9.0.98.wso2v1

---

api-common/2.42.0.wso2v1/pom.xml
failureaccess/1.0.2.wso2v1/pom.xml
firebase-admin/9.4.1.wso2v1/pom.xml
firebase-admin/9.4.2.wso2v1/pom.xml

$subject
This jar is added to the orbit for the purpose of using it for push notification based authentication in identity server using Firebase Cloud Messaging.

Add Firebase-admin jar to orbit

---

httpclient5/5.4.1.wso2v1/pom.xml
httpcore5/5.3.1.wso2v1/pom.xml
pom.xml

Add latest versions of httpclient5 and httpcore5

---

graal-sdk/22.3.4.wso2v1/pom.xml

Add graal-sdk 22.3.4.wso2v1

---

graal-sdk/22.3.4.wso2v1/pom.xml

Update license year for graal-sdk dependency

---

netty/4.1.115.wso2v1/pom.xml
vertx-json-schema/4.5.11.wso2v1/pom.xml

> $Subject
> https://github.com/wso2/product-is/issues/22252

Add vertx-json-schema 4.5.11 and bump netty-all to 4.1.115

---

firebase-admin/9.4.2.wso2v2/pom.xml

Add firebase admin v9.4.2.wso2v2

---

firebase-admin/9.4.2.wso2v2/pom.xml

Modify firebase admin 9.4.2.wso2v2

---

google-auth-library-oauth2-http/1.20.0.wso2v2/pom.xml

Introduce google-auth-library-oauth2-http v1.20.0.wso2v2

---

azure-messaging-servicebus-sdk-all/7.17.8.wso2v1/pom.xml

$subject to have latest version.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

Add azure-service-bus-sdk version 7.17.8

---

azure-messaging-servicebus-sdk-all/7.17.8.wso2v2/pom.xml

$subject as wso2v1 has issues due to conflicts in io.netty packages
> Link(s) to product documentation that addresses the …

Add latest ASB client sdk version to avoid errors in event publishing 7.17.8 wso2v2

---

zipkin-sender-okhttp3/2.17.2.wso2v2/pom.xml

Add zipkin-sender-okhttp3 v2.17.2.wso2v2

---

openapi-generator/7.11.0.wso2v1/pom.xml

> Add openAPI generator v7.11.0.

Add openAPI generator 7.11.0.

---

netty/4.1.115.wso2v1/pom.xml

> $Subject
> https://github.com/wso2/product-is/issues/22735

Add netty-resolver-dns-native-macos runtime dependency to netty-all

---

commons-compress/1.27.1.wso2v1/pom.xml
pom.xml

Add commons-compress 1.27.1.wso2v1

---

okhttp/4.9.3.wso2v5/pom.xml

We need to bump the kotlin version to >2.1.0 to avoid a vulnerability https://security.snyk.io/vuln/SNYK-JAVA-ORGJETBRAINSKOTLIN-2393744.
Public issue - https://github.com/wso2/product-micro-integrator/issues/3993
Support issue - https://github.com/wso2-enterprise/wso2-mi-internal/issues/1289
> Brief description of the new feature or bug fix as it will appear in the …

Bump the kotlin-stdlib version of okhttp-4.9.3 to 2.1.10

---

netty/4.1.115.wso2v2/pom.xml

Fix https://github.com/wso2/product-is/issues/22735

Add a new version of netty-all with netty-resolver-dns-native-macos runtime dependency

---

tomcat-catalina-ha/9.0.100.wso2v1/pom.xml
tomcat-el-api/9.0.100.wso2v1/pom.xml
tomcat-jsp-api/9.0.100.wso2v1/pom.xml
tomcat-servlet-api/9.0.100.wso2v1/pom.xml
tomcat/9.0.100.wso2v1/pom.xml
tomcat/9.0.100.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat 9.0.100.wso2v1

---

okhttp/4.12.0.wso2v2/pom.xml

We need to bump the kotlin version to >2.1.0 to avoid a vulnerability [security.snyk.io/vuln/SNYK-JAVA-ORGJETBRAINSKOTLIN-2393744](https://security.snyk.io/vuln/SNYK-JAVA-ORGJETBRAINSKOTLIN-2393744).
Public issue - https://github.com/wso2/product-micro-integrator/issues/3993
The 4.9.3 version PR - https://github.com/wso2/orbit/pull/1185
> Brief description of the new …

Add ookhttp-4.12.0.wso2v2 with kotlin 2.1.10

---

swagger-request-validator-v3/2.44.1.wso2v1/pom.xml
swagger-request-validator/2.12.1.wso2v4/pom.xml

> Add swagger request validator 2.44.1.wso2v1

Add swagger request validator (OAS 3 only) 

---

tomcat-catalina-ha/9.0.102.wso2v1/pom.xml
tomcat-el-api/9.0.102.wso2v1/pom.xml
tomcat-jsp-api/9.0.102.wso2v1/pom.xml
tomcat-servlet-api/9.0.102.wso2v1/pom.xml
tomcat/9.0.102.wso2v1/pom.xml
tomcat/9.0.102.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add Apache Tomcat 9.0.102.wso2v1 orbit bundles

Add Apache Tomcat 9.0.102.wso2v1 orbit bundles

---

okio/3.9.0.wso2v2/pom.xml

$ subject
Tested the functionality of MI 4.2.0 with this and works as expected. …

Add okio-3.9.0.wso2v2 with kotlin 2.1.10

---

opensaml/2.6.6.wso2v8/pom.xml

Add OpenSaml with ESAPI v2.6.0.0

---

solr/9.8.1.wso2v1/pom.xml

Add Apache Solr v9.8.1

---

json/3.0.0.wso2v6/pom.xml

This pull request introduces a new `pom.xml` file for the `json/3.0.0.wso2v6` package, setting up the Maven project configuration for the WSO2 Carbon Orbit JSON library. The file includes metadata, repository configurations, dependencies, build instructions, and project properties.

Add JSON 3.0.0.wso2v6

---

opencsv/5.10.wso2v1/pom.xml

Add opencsv 5.10.wso2v1 bundle

---

spring-framework/5.3.39.wso2v1/pom.xml

Add review suggestions

---

kafka-avro-serializer/7.9.0.wso2v1/pom.xml
kafka-schema-registry-client/7.9.0.wso2v1/pom.xml
kafka-schema-serializer/7.9.0.wso2v1/pom.xml

Add kafka-avro-serializer, kafka-schema-serializer, and kafka-schema-registry-client 7.9.0.wso2v1 bundle

---

jsch/0.2.24.wso2v1/pom.xml

Add jsch 0.2.24.wso2v1 bundle

---

bctls/1.80.0.wso2v2/pom.xml

Related pr https://github.com/wso2/orbit/pull/1202

Add bctls 1.80 v2

---

tomcat-catalina-ha/9.0.105.wso2v1/pom.xml
tomcat-el-api/9.0.105.wso2v1/pom.xml
tomcat-jsp-api/9.0.105.wso2v1/pom.xml
tomcat-servlet-api/9.0.105.wso2v1/pom.xml
tomcat/9.0.105.wso2v1/pom.xml

Add following components
tomcat: v9.0.105
tomcat-catalina-ha: v9.0.105
tomcat-el-api: v9.0.105
tomcat-jsp-api: v9.0.105
tomcat-servlet-api: v9.0.105

Add Apache Tomcat Components for v9.0.105

---

pulsar/4.0.4.wso2v1/pom.xml

Add Pulsar orbit bundle

---

commons-compress/1.27.1.wso2v2/pom.xml

fix: https://github.com/wso2/product-micro-integrator/issues/4202

Update commons compress import package 

---

poi-ooxml/5.4.1.wso2v1/pom.xml
poi-scratchpad/5.4.1.wso2v1/pom.xml
poi/5.4.1.wso2v1/pom.xml

Update apache poi, poi-ooxml and poi-scratchpad to 5.4.1

---

commons-beanutils/1.11.0.wso2v1/pom.xml
tiles/2.0.5.wso2v3/pom.xml
tiles/2.0.5.wso2v3/src/main/java/org/wso2/carbon/tiles/CarbonUrlDefinitionsFactory.java
tiles/2.0.5.wso2v3/src/main/resources/META-INF/tiles-jsp.tld

This PR adds new orbit bundles for commons-beanutils (1.11.0.wso2v1) and  tiles-jsp (2.0.5.wso2V3).

Add new bundles for beanutil and tiles-jsp

---

tomcat-catalina-ha/9.0.106.wso2v1/pom.xml
tomcat-el-api/9.0.106.wso2v1/pom.xml
tomcat-jsp-api/9.0.106.wso2v1/pom.xml
tomcat-servlet-api/9.0.106.wso2v1/pom.xml
tomcat/9.0.106.wso2v1/pom.xml
tomcat/9.0.106.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

> Add tomcat 9.0.106 related orbit bundles

Add tomcat 9.0.106

---

pulsar/4.0.4.wso2v2/pom.xml

Add pulsar client 4.0.4.wso2v2

---

nimbus/10.3.0.wso2v1/pom.xml
pom.xml

$subject
Release the new nimbus jose jwt orbit version
https://github.com/wso2/product-is/issues/23582

Add nimbus jose jwt 10.3 version

---

solr/9.8.1.wso2v3/pom.xml

- Bump jetty version to v10.0.25

Add pom.xml for solr-9.8.1.wso2v3

---

commons-fileupload/1.6.0.wso2v1/pom.xml

Issue:
- https://github.com/wso2/product-is/issues/24705

Add new commons-fileupload 1.6.0.wso2v1 version

---

yubico-webauthn/2.5.1.wso2v1/pom.xml

Add yubico-webauthn 2.5.1.wso2v1

---

pom.xml
yubico-webauthn/1.10.1.wso2v4/pom.xml

$subject
Local Check:
This PR should be merged after the Maven release of edsa:0.3.0.wso2v1 is completed.
- https://github.com/wso2/wso2-ed25519-java
- https://wso2.org/jenkins/job/forked-dependencies/job/wso2-ed25519-java/

Introduce yubico 1.10.1.wso2v4 with in-house eddsa

---

tomcat-catalina-ha/9.0.109.wso2v1/pom.xml
tomcat-el-api/9.0.109.wso2v1/pom.xml
tomcat-jsp-api/9.0.109.wso2v1/pom.xml
tomcat-servlet-api/9.0.109.wso2v1/pom.xml
tomcat/9.0.109.wso2v1/pom.xml
tomcat/9.0.109.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat dependencies v9.0.109.wso2v1

Add tomcat dependencies v9.0.109.wso2v1

---

azure-resourcemanager-apimanagement/2.0.0.wso2v3/pom.xml

Adds some dependencies required for Azure Federation in ACP as private package.

Add azure resource manager 2.0.0.wso2v3 orbit pom file.

---

pom.xml
solr/9.5.0.wso2v10/pom.xml

> ${Subject}
- https://github.com/wso2/product-is/issues/25789

Bump zookeeper version in solr 9.5

---

pom.xml
solr/9.9.0.wso2v2/pom.xml

Bump zookeeper version to 3.9.4 in solr 9.9.0

---

azure-resourcemanager-apimanagement/2.0.0.wso2v4/pom.xml

- Remove netty dependencies which were added as private packages

Add azure-resourcemanager-apimanagement 2.0.0.wso2v4

---

tomcat-catalina-ha/9.0.110.wso2v1/pom.xml
tomcat-el-api/9.0.110.wso2v1/pom.xml
tomcat-jsp-api/9.0.110.wso2v1/pom.xml
tomcat-servlet-api/9.0.110.wso2v1/pom.xml
tomcat/9.0.110.wso2v1/pom.xml
tomcat/9.0.110.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

Add tomcat dependencies v9.0.110.wso2v1
