membrane-soa-model/1.5.0.wso2v3/pom.xml

add new version of membrane-soa-model 1.5.0.wso2v3 with by exporting groovy.util.* and  groovy.lang.*

add new version of membrane-soa-model 1.5.0.wso2v3

---

hadoop-client/2.6.0.wso2v3/pom.xml
pom.xml

This change fixes an OSGI issue that pops up due to hadoop client using a version of guava library that is not constrained. The issue was encountered when installing DAS features along with MB (MB uses a higher version of guava). Hence the version range is constrained to [15.0.0, 16.0.0).

Adding new version of hadoop client with import constrains

---

swagger-codegen/2.2.0.wso2v2/pom.xml

This version is needed for SDK generation in APIM because the updated version of the codegen library must have support for ".swagger-codegen-ignore" file.
See : https://github.com/swagger-api/swagger-codegen/commit/21e2b7bb2a10b1592ba89f1e5868d1405e8bb905

Including the fix for SDK generation for swagger-codegen - 2.2.0.wso2v2 orbit release.

---

kubernetes-client/2.5.2.wso2v1/pom.xml
okhttp-ws/3.8.0.wso2v1/pom.xml
okhttp/3.8.0.wso2v1/pom.xml
okio/1.13.0.wso2v1/pom.xml

This PR adds Orbit bundles for the following libraries and versions.
1. okhttp - `3.8.0.wso2v1`
2. okhttp-ws - `3.8.0.wso2v1`
3. okio - `1.13.0.wso2v1`
At the same time, the OSGi import ranges for the above has been adjusted in the kubernetes-client `2.5.2.wso2v1` bundle.

K8S Client - okhttp and okio Orbit bundles

---

quartz/2.3.0.wso2v1/pom.xml

This PR will add Quartz 2.3.0 to WSO2 Orbit.

Add Quartz 2.3.0 to WSO2 Orbit

---

swagger-codegen/2.2.3.wso2v1/pom.xml
swagger-parser/1.0.32.wso2v1/pom.xml

Update swagger-codegen and swagger-parser to support SDK generation feature of API Manager
- swagger-codegen 2.2.0.wso2v3 --> 2.2.3.wso2v1
- swagger-parser 1.0.21.wso2v2 --> 1.0.32.wso2v1

Update swagger-codegen to 2.2.3.wso2v1, swagger-parser to 1.0.32.wso2v1

---

geronimo-saaj_1.3_spec/1.0.1.wso2v2/pom.xml

Changed geeonimo-saaj javax.xml.soap export version to 1.0.0
* Change geeonimo-saaj javax.xml.soap export version to 1.0.0

Change geeonimo-saaj javax.xml.soap export version

---

commons-codec/1.4.0.wso2v1/pom.xml

Upgrade the commons-codec dependency version to 1.10
Upgrade the commons-codec dependency version to 1.10
Upgrade the commons-codec dependency version from 1.4 to 1.10
- Unit tests 
N/A
- Integration tests
N/A

Upgrade common-codec dependency

---

tomcat-catalina-ha/7.0.82.wso2v1/pom.xml
tomcat-el-api/7.0.82.wso2v1/pom.xml
tomcat-jsp-api/7.0.82.wso2v1/pom.xml
tomcat-servlet-api/7.0.82.wso2v1/pom.xml
tomcat/7.0.82.wso2v1/pom.xml
tomcat/7.0.82.wso2v1/src/main/resources/META-INF/services/javax.el.ExpressionFactory

> This PR contains changes to upgrade the tomcat version to 7.0.82 for kernel 4.4.1.
> To overcome the regression issues in Tomcat 7.0.81.
> Upgrade the tomcat version to 7.0.82
> As the system, we need to overcome the regression issues in tomcat 7.0.81
> Orbit bundles for tomcat are upgraded to 7.0.82
> N/A
> N/A
> > N/A
> N/A
- Integration tests
> Run the integration tests on AS-5.3.0 which uses these orbit bundles
- Ran FindSecurityBugs plugin and verified report? N/A
> N/A
> N/A
> Tomcat version upgrade
> N/A
> N/A

Upgrade tomcat version to 7.0.82 for kernel 4.4.1

---

csrfguard/3.1.0.wso2v3/pom.xml

> As per [this issue](https://github.com/wso2/product-is/issues/1956) the CSRFGuard library is affected with JDK-8189789 bug. This PR has been created to wrap a new release of CSRFGuard which avoids the code affected by JDK-8189789.
> To let the users with any environment (e.g. MacOS HighSierra, JDK 8 any update) to run WSO2 products without an issue.
> Forking the library code and modifying the HTTP response generating code to prevent manipulating the output stream directly.

product-is:1956 Adding csrfguard-3.1.0.wso2v3

---

commons-fileupload/1.3.3.wso2v1/pom.xml

> Apache-commons -fileupload version 1.3.1 and 1.3.2 are vulnerable to CVE-2016-3092. Therefore this is to upgrade the fileupload version to 1.3.3

Add apache commons file upload 1.3.3 version

---

activation/1.1.1.wso2v1/pom.xml
jaxb-api/2.3.1.wso2v1/pom.xml
pom.xml

Javax packages are completely removed from JDK-11 onwards. Therefore these packages should be added as orbit bundles to use when building wso2 components using JDK-11.

 Add javax-activation and jaxb-api as orbit bundles

---

json-schema-validator-all/2.2.6.wso2v5/pom.xml

> This upgrades the json.schema.core.version in json-schema-validator-all from 1.2.5 to 1.2.8
> New version has set a cache size to the caching processor inside  json-schema-core

Upgrade json.schema.core.version

---

tomcat-jsp-api/9.0.21.wso2v1/pom.xml
tomcat-servlet-api/9.0.21.wso2v1/pom.xml
tomcat/9.0.21.wso2v1/pom.xml

> Revert javax.servlet and org.apache.jasper export version. The reason is the current equinox.http.servlet version expects these range. Updating the equinox.http.servlet version is not possible currently as the current servlet bridging needs to be rewritten with new implementation

Revert javax.servlet and org.apache.jasper export version

---

js/1.7.0.R5.wso2v1/pom.xml

Adding js/1.7.0.R5.wso2v1 module with the following dependency,
```
<dependency>
<groupId>org.mozilla</groupId>
<artifactId>rhino</artifactId>
<version>1.7R5</version>
</dependency>
```

Add js/1.7.0.R5.wso2v1 module

---

grpc-netty-shaded/1.26.0.wso2v1/pom.xml
grpc-protobuf/1.26.0.wso2v1/pom.xml
grpc-stub/1.26.0.wso2v1/pom.xml

This PR adds following orbit bundles:
1. grpc-netty-shaded - 1.26.0.wso2v1
2. grpc-protobuf - 1.26.0.wso2v1
3. grpc-stub - 1.26.0.wso2v1 

Add io grpc related library modules

---

yubico-webauthn/1.3.0.wso2v3/pom.xml

This PR will add the new version **1.3.0.wso2v3** for the `yubico-webauthn` orbit bundle. This version will not bundle the `org.bouncycastle:bcprov-jdk15on` library inside yubico-webauthn jar.

Add new wso2 version of yubico-webauthn

---

swagger-parser/2.0.13.OpenAPITools.wso2v1/pom.xml

Fixes: https://github.com/wso2/product-apim/issues/7893
Fixes: https://github.com/wso2/product-apim/issues/8185
Update the swagger-parser with [2.0.13.OpenAPITools.org-2](https://github.com/OpenAPITools/swagger-parser/releases/tag/v2.0.13-OpenAPITools.org-2)
- Changed the pom of 2.0.13.OpenAPITools.wso2v1 with [2.0.13.OpenAPITools.org-2](https://github.com/OpenAPITools/swagger-parser/releases/tag/v2.0.13-OpenAPITools.org-2). 
- Only the internal packages in the pom have been changed. The name of the orbit package will remain as 2.0.13.OpenAPITools.wso2v1 without a change.

Upgrade the version of swagger parser to 2.0.13-OpenAPITools.org-2 without changing the package name 2.0.13.OpenAPITools.wso2v1 

---

swagger-parser/2.0.13.OpenAPITools.wso2v1/pom.xml

Reverts wso2/orbit#423
**Reason**: Currently, we  have 2.0.13.OpenAPITools.wso2v1 [1] swagger parser which was created from OpenAPITools [2] (which is a forked directory of the base swagger parser in [3]). The latest OpenAPITool swagger parser version is 2.0.14-OpenAPITools.org-1 [4] which is based on the base swagger parser release 2.0.14 [5]. Still, OpenAPITools has not done a release for base swagger parser latest version which is 2.0.20. 
So, our aim is to revert the PR wso2/orbit#423 and move to the previous version, until we find a way to incorporate the latest version (2.0.20) of the base swagger parser, directly.
[1]. https://github.com/wso2/orbit/tree/master/swagger-parser/2.0.13.OpenAPITools.wso2v1
[2]. https://github.com/OpenAPITools/swagger-parser/
[3]. …

Revert "Upgrade the version of swagger parser to 2.0.13-OpenAPITools.org-2 without changing the package name 2.0.13.OpenAPITools.wso2v1 "

---

jaeger-client/0.32.0.wso2v3/pom.xml

> - Add jaeger-client 0.32.0.wso2v3. 
javax.annotation version has been upgraded from `[0.0.0,1.0.0)`(default import version) to `[1.0.0,2.0.0)`, in order to be able to pack jaeger-client with WSO2 Micro Integrator.

Add jaeger-client 0.32.0.wso2v3

---

commons-lang/3.11.0.wso2v1/pom.xml
jaxb-api/2.3.1.wso2v2/pom.xml
pom.xml

> Add commons lang 3 new version
Add jaxb-api patch version which is exporting the exact version (2.3.1)
rather than 0.0.0
Related to wso2/micro-integrator/issues/2043

Add dependency bundles required by swagger-core v3

---

httpmime/4.5.13.wso2v1/pom.xml
openid4java/1.0.0.wso2v5/pom.xml
yubico-webauthn/1.10.0.wso2v1/pom.xml
yubico-webauthn/1.10.1.wso2v1/pom.xml

1. Support latest yubico version.
2. Latest yubico depending on http client version higher than 4.5 hence packing the httpclient version 4.5.13 instead of httpclient 4.3.6 (4.5.13 is already available in the master branch)
2. httpclient is depending on http core. http client 4.5.13 expecting http core version to be higher than 4.4. Therefore updated the httpcore version to 4.4.14.(4.4.14 is already available in the master branch)
3. httpmime is depending on httpcore. Therefore updated httpmime from 4.3.1 to 4.5.13
4. Updated openid4java since old openidjava is expecting old versions of httpclient and httpcore(updated httpclient, httpcore version to the latest one)

Add latest httpmime, openid4java, yubico version

---

tomcat/9.0.52.wso2v2/pom.xml
tomcat/9.0.52.wso2v2/src/main/resources/META-INF/services/javax.el.ExpressionFactory

When upgrading tomcat-embed-core from 9.0.36 -> 9.0.37, our tomcat orbit bundle picks up an import version range of [1.3, 2) for javax.annotation dependency. In WSO2 products we expose the javax.annotation dependency as 0.0.0 via eclipse.osgi bundle. If a wrong javax.annotation dependency (eg: javax.annotation-api_1.3.2) is picked up by tomcat bundle, it may lead to ClassNotFound issues when invoking webapps that are deployed inside tomcat.
[1] - apache/tomcat#306

Create tomcat 9.0.52 bundle with javax.annotation import

---

opensaml/3.3.1.wso2v2/pom.xml
opensaml/3.3.1.wso2v3/pom.xml
pom.xml

Update the esapi version embedded in opensaml to non-vulnerable v2.2.3.1 
Related to https://github.com/wso2/product-is/issues/12489

Update esapi version in opensaml

---

pom.xml
ua-parser/1.5.2.wso2v1/pom.xml

Resolves - [#12780](https://github.com/wso2/product-is/issues/12780)
> In the limiting active user session feature, it displays the current active sessions with browser family in the browser column. When we have a logged in session with Microsoft edge, it shows the browser as chrome.
> In this feature, we used the ua-parser library to extract these user-agent details. But the mentioned issue is already identified in the ua-parser 1.3.0 and it has been fixed and released as a new version. So issue is fixed by upgrading to ua-parser 1.5.2.

Add ua-parser 1.5.2.wso2v1

---

pom.xml
yubico-webauthn/1.12.1.wso2v1/pom.xml

Upgrade **yubico-webauthn** version from `1.10.1.wso2v2` to `1.12.1.wso2v1`.
The **com.upokecenter:cbor** version is also upgraded to `4.5.2` along with this.
Related to: wso2/product-is#13048

Upgrade yubico-webauthn version

---

json-schema-validator-all/2.2.6.wso2v8/pom.xml
openapi-generator/4.3.1.wso2v4/pom.xml

This PR adds new orbit bundles for json-schema-validator `2.2.6.wso2v8` and openapi-generator `4.3.1.wso2v4`.

Add new orbit bundles for json-schema-validator and openapi-generator

---

swagger-inflector/2.0.5.wso2v2/pom.xml
waffle/1.6.wso2v7/pom.xml

This PR adds new bundles for swagger-inflector (`2.0.5.wso2v2`) and waffle (`1.6.wso2v7`). This is to upgrade the guava version.

Add new swagger inflector and waffle bundles

---

commons-beanutils/1.9.4.wso2v1/pom.xml
commons-scxml/0.9.0.wso2v2/pom.xml

This PR adds new orbit bundles for commons-beanutils (`1.9.4.wso2v1`) and commons-scxml (`0.9.0.wso2v2`).

Add new bundles for beanutils and scxml

---

google-api-client/1.33.1.wso2v1/pom.xml
google-http-client/1.41.2.wso2v1/pom.xml
google-oauth-client/1.33.1.wso2v1/pom.xml
quartz/2.3.2.wso2v1/pom.xml

This PR will add the following to orbit,
- google-oauth-client 1.33.1
- google-api-client 1.33.1
- google-http-client 1.41.2
- quartz 2.3.2

Upgrade google clients and quartz

---

jstl/1.2.1.wso2v3/pom.xml

This PR adds the new orbit bundle `jstl_1.2.1.wso2v3`. Here, the Apache Standard Taglibs version is upgraded to 1.2.5.

Add new orbit bundle for jstl

---

okhttp/4.9.3.wso2v1/pom.xml
okio/2.8.0.wso2v1/pom.xml

When upgrading okhttp to version 4.9.3.wso2v1 in APIM, it needs a new okio version 2.8.0.wso2v1. Hence, adding both the bundles.
Adding new okio 2.8.0.wso2v1 and okhttp 4.9.3.wso2v1 bundles
- The new okhttp 4.9.3.wso2v1 will contain new okhttp 4.9.3, kotlin 1.4.10 and mockwebserver.version 4.9.3.
- The new okio 2.8.0.wso2v1 will contain new okio 2.8.0 and kotlin 1.4.10.

Adding new okio 2.8.0.wso2v1 and okhttp 4.9.3.wso2v1 bundles

---

solr/8.11.1.wso2v1/pom.xml

> Bump Jetty-HTTP version in solr_8.11.1.wso2v1 to 9.4.48.v20220622

Upgrade jetty version to 9.4.48.v20220622

---

poi-ooxml/5.2.3.wso2v1/pom.xml

- Adding poi-ooxml latest version 5.2.3[1] as an orbit bundle
- Referrence[2]
[1] https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml/5.2.3
[2] https://github.com/wso2/orbit/blob/master/poi-ooxml/3.9.0.wso2v3/pom.xml

Add poi-ooxml 5.2.3 wso2 bundle

---

poi/5.2.3.wso2v1/pom.xml

- Adding poi latest version 5.2.3[1] as an orbit bundle
- Referrence [2]
[1] https://mvnrepository.com/artifact/org.apache.poi/poi/5.2.3
[2] https://github.com/wso2/orbit/blob/master/poi/3.17.0.wso2v1/pom.xml

Add poi 5.2.3 wso2 bundle

---

kafka-avro-serializer/7.3.1.wso2v1/pom.xml
kafka-schema-registry-client/7.3.1.wso2v1/pom.xml

Add bundles for kafka schema registry and kafka avro serializer in order to fix OSGI import issues
Add new bundles 

Add orbit bundles for kafka schema registry and kafka avro serializer

---

commons-net/3.9.0.wso2v1/pom.xml
pom.xml

This PR adds a new orbit bundle for commons-net `3.9.0`.
Related issue: https://github.com/wso2/api-manager/issues/1251

Add orbit bundle for commons-net 3.9.0.wso2v1

---

google-api-client/1.33.1.wso2v2/pom.xml
google-http-client/1.41.2.wso2v2/pom.xml
grpc-contex/1.27.2.wso2v1/pom.xml
opencensus/0.30.0.wso2v1/pom.xml

This PR will add the following to orbit,
- opencensus 0.30.0
- grpc-contex 1.27.2
Update the following to wso2v2,
- google-api-client 1.33.1.wso2v2 contains `com.google.api.client.json.gson` as an Import-Package
- google-http-client 1.41.2.wso2v2 packs `google-http-client-gson` and `google-http-client-apache-v2`

Upgrade google clients and add opencensus, grpc-context

---

swagger-codegen/2.4.30.wso2v1/pom.xml

Due to two below vulnerabilities, swagger-codegen must be upgrade to newer version which does not contain vulnerabilities.
- CVE-2021-21363
- CVE-2021-21364 
So 2.4.30.wso2v1 will be released with swagger-codegen 2.4.30 which is the latest.

Swagger Codegen 2.4.30.wso2v1

---

openapi-generator/4.3.1.wso2v1.1/pom.xml
swagger-inflector/1.0.16.wso2v2/pom.xml
swagger-parser/2.0.20.wso2v2/pom.xml

This PR will create new versions for the below three dependency bundles.
***swagger-parser/2.0.20.wso2v2***
This version contains swagger core version 1.6.9 to fix the known vulnerabilities
***swagger-inflector/1.0.16.wso2v2***
This version also contains swagger core version 1.6.9 to fix the known vulnerabilities
***openapi-generator/4.3.1.wso2v1.1***
This version of openapi-generator includes guava version range extension to fix the OSGI issues after upgrading swagger core versions to 1.6.9 in API Manager-3.2.0

Introduce new bundles with swagger core upgrade

---

swagger-codegen/2.4.30.wso2v2/pom.xml

To wso2am-4.0.0 to correctly functioning, swagger-models is also needed inside swagger-codegen when it comes to new versions. This was identified through an integration test failure and found out that SOAP rest api creation is not working properly with out this.  
`Caused by: java.lang.ClassNotFoundException: io.swagger.models.Responses cannot be found by swagger-codegen_2.4.30.wso2v1  `
Since both dependencies are from io.swagger and swagger-models does not contain any direct vulnerabilities, adding that to wso2v2 version.

Swaggger Codegen 2.4.30.wso2v2

---

okhttp/4.9.3.wso2v3/pom.xml
okio/2.8.0.wso2v3/pom.xml

Upgrading Okhttp 4.9.3 and Okio 2.8.0's kotlin version to 1.8.10

Upgrading Okio and Okhttp version

---

libthrift/0.14.2.wso2v1/pom.xml

This PR adds `libthrift 0.14.2.wso2v1` orbit bundle.

Add libthrift 0.14.2.wso2v1

---

jsonpath/2.6.0.wso2v2/pom.xml

Upgrading the vulnerable[1] json-smart version (v2.4.7) used in json-path 2.6.0.wso2v1 to the latest json-smart version (v2.4.11)
[1] https://nvd.nist.gov/vuln/detail/CVE-2023-1370

Add json-path 2.6.0.wso2v2

---

openapi-generator/4.3.1.wso2v5/pom.xml
swagger-core/1.6.9.wso2v2/pom.xml

This PR adds `openapi-generator-4.3.1.wso2v5` and `swagger-core-1.6.9.wso2v2`. 

Add openapi-generator-4.3.1.wso2v5 and swagger-core-1.6.9.wso2v2

---

json-schema-validator-all/2.2.6.wso2v8/pom.xml

- Fixed issue of the guava bump to the latest version for apim 4.1.0
- Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/3535
- Add version range such that all methods import the same code base of the `com.google.common.base.Equivalence`

Bump the google common range to [31.0.0, 33.0.0)

---

openapi-generator/4.3.1.wso2v5/pom.xml

- Fixed issue in version alignment issue with previously released 4.3.1.wso2v4 version.
- Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/3535
- Add version ranges from 4.3.1.wso2v4.

Update pom changes aligning with 4.3.1.wso2v4 version

---

openapi-generator/4.3.1.wso2v6/pom.xml

> $Subject. Fixes https://github.com/wso2/api-manager/issues/2165
Overall, only the `<google.version.range>[31.0.0,33.0.0)</google.version.range>` is now different, when compared with `4.3.1.wso2v4`. 
Below will be the resultant diff between the `pom.xml` files `4.3.1.wso2v4` and the added `4.3.1.wso2v6`
```diff
...		
<modelVersion>4.0.0</modelVersion>	
<groupId>org.wso2.orbit.org.openapitools</groupId>	
<artifactId>openapi-generator</artifactId>
-   <version>4.3.1.wso2v4</version>
+   <version>4.3.1.wso2v6</version>
...
<properties>
-        <export.pkg.version.swagger-codegen>4.3.1.wso2v4</export.pkg.version.swagger-codegen>
+        <export.pkg.version.swagger-codegen>4.3.1.wso2v6</export.pkg.version.swagger-codegen>
...
- …
```

Add openapi-generator 4.3.1.wso2v6

---

google-api-client/2.2.0.wso2v1/pom.xml
google-api-services-play-integrity/2.0.0.wso2v1/pom.xml
google-auth-library-oauth2-http/1.20.0.wso2v1/pom.xml
google-http-client/1.43.3.wso2v1/pom.xml
grpc-contex/1.59.0.wso2v1/pom.xml
opencensus/0.31.1.wso2v1/pom.xml

Issue: https://github.com/wso2/product-is/issues/16836
Add jars to support Android PlayIntegrity Client Attestation Service.
google-api-services-playintegrity jar version changed to 2.0.0 cause the original version is "v1-rev20231018-2.0.0" and its not compatible for eclispe plugin installment by causing numeric exveption

jars for android client attestation

---

commons-compress/1.25.0.wso2v1/pom.xml

- Adding commons-compress latest version 1.25.0[1] as an orbit bundle
- Referrence [2]
[1] https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.25.0
[2] https://github.com/wso2/orbit/blob/master/commons-compress/1.22.0.wso2v1/pom.xml
- https://github.com/wso2/product-is/issues/18099

Add commons-compress 1.25.0 wso2 bundle

---

apacheds/2.0.0.AM27.wso2v1/pom.xml

- apacheds protocol kerberos doesn't have the version 2.0.0.AM27
- To fix that add the latest release version of apacheds protocol kerberos 2.0.0.AM26 to the pom file

Fix the missing apacheds protocol kerberos version issue in apacheds orbit jar

---

bcpkix/1.77.0.wso2v2/pom.xml

This PR adds bcpkix:1.77.0.wso2v2 version

Add bcpkix:1.77.0.wso2v2 version

---

h2-engine/2.2.224.wso2v2/pom.xml
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/H2DatabaseServiceActivator.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/console/ConsoleService.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/console/H2DatabaseManager.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/database/H2DatabaseManager.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonConstants.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/utils/CarbonUtils.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Constants.java
h2-engine/2.2.224.wso2v2/src/main/java/org/wso2/carbon/h2/osgi/utils/H2Utils.java

- This PR fixes the package folder structure issue in h2-engine `2.2.224.wso2v1`. 
- In the above h2-engine version, `console` folder which should be situated inside the `wso2/carbon/h2/osgi` folder, is situated outside the said folder [1].
[1] - https://github.com/wso2/orbit/tree/master/h2-engine/2.2.224.wso2v1/src/main/java/org/console

Add H2 Engine Version `2.2.224.wso2v2`

---

jsonpath/2.9.0.wso2v1/pom.xml

Upgrade the jsonpath to latest level (2.9.0) with json-smart 2.5.0
```diff
...	
-           <dependency>
-                 <groupId>net.minidev</groupId>
-                 <artifactId>json-smart</artifactId>
-                 <version>${net.mindev.jsonsmart.version}</version>
-            </dependency>	
-            <dependency>
-                  <groupId>net.minidev</groupId>
-                  <artifactId>asm</artifactId>
-                  <version>${net.mindev.asm.version}</version>
-             </dependency>
...
-            <Bundle-SymbolicName>${pom.artifactId}</Bundle-SymbolicName>
-            <Bundle-Name>${pom.artifactId}</Bundle-Name>
+            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
+            <Bundle-Name>${project.artifactId}</Bundle-Name> …
```

JSON path 2.9.0

---

pdfbox-io/3.0.1.wso2v1/pom.xml

- For the dependency upgrade process of pdfbox to 3.0.1, there is an extra import needed for pdfbox-io dependency.
- As per the https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox-io this is a new requirement came for 3.x versions.
- In the pdfbox-io `MANIFEST.MF`, there is an additional import for sun-misc which is not been even used in the code itself.
- This gives an OSGi error as the sun.misc is not currently exported from any of the packages in the pack.
- Related to https://github.com/wso2/carbon-apimgt/pull/12251
- Removed the sun.misc dependency by orbiting the pdfbox-io

Add pdfbox-io as a orbit dependency to exclude sun.misc import

---

openapi-generator/4.3.1.wso2v8/pom.xml
swagger-parser/2.1.18.wso2v2/pom.xml
swagger-request-validator/2.12.1.wso2v3/pom.xml

To ensure compatibility with the latest non-vulnerable version of Guava 33.0.

Add openapi-generator version 4.3.1.wso2v8

---

solr/5.5.5.wso2v4/pom.xml

This PR adds the Solr version 5.5.5.wso2v4 updated commons.io version range.
https://github.com/wso2-enterprise/wso2-apim-internal/issues/7371

Add solr 5.5.5.wso2v4 dependency with updated commons.io version range

---

commons-io/2.17.0.wso2v1/pom.xml
swagger-parser/2.1.13.wso2v2/pom.xml

This PR adds the following dependencies,
- [Add commons-io 2.17.0.wso2v1 dependency](https://github.com/wso2/orbit/commit/95f2c31ac42b7222a1c48cdaacf59552f0903d16)
- [Add swagger-parser v2.1.13.wso2v2 dependency](https://github.com/wso2/orbit/commit/401f84a752f8a82ba8419e42ff4bdcb0b3fd9c60) (Removing commons-io embedded dependency)
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/7371

Add commons-io 2.17.0.wso2v1 and swagger-parser 2.1.13.wso2v2 depdendenices

---

azure-messaging-servicebus-sdk-all/7.14.6.wso2v1/pom.xml
azure-messaging-servicebus-sdk-all/7.14.6.wso2v2/pom.xml

Export transitive dependencies required for admin client in azure-messaging-servicebus-sdk-all.

Add new version to azure-messaging-servicebus-sdk-all : 7.14.6.wso2v2

---

swagger-parser/2.1.20.wso2v2/pom.xml

To add swagger-parser 2.1.20.wso2v2 with commons-io version upgrade.

Add swagger-parser 2.1.20.wso2v2 with commons-io version upgrade

---

swagger-parser/2.1.18.wso2v4/pom.xml

To add swagger-parser 2.1.18.wso2v4 with commons-io version upgrade.

Add swagger-parser 2.1.18.wso2v4 with commons-io version upgrade

---

netty/4.1.115.wso2v1/pom.xml

Reverts wso2/orbit#1180
Need to release this orbit in different version

Revert "Add netty-resolver-dns-native-macos runtime dependency to netty-all"

---

aws-core/2.30.22.wso2v1/pom.xml

Implement AWS-Core Orbit for the AWS gateway Agent and the AWS Lambda Mediator. Lambda mediator previously used the AWS SDK version 1. From this implementation onwards it uses the AWS SDK V2.

AWS Core Orbit Implementation

---

swagger-parser/2.1.25.wso2v1/pom.xml

- To add the swagger-parser 2.1.25.wso2v1 bundles which includes the latest version of io.swagger.parser.v3 : swagger-parser (2.1.25)

Add swagger-parser 2.1.25.wso2v1

---

swagger-parser/2.1.25.wso2v2/pom.xml

Add a minor version for swagger-parser orbit version 2.1.25 with export package version containing the corresponding orbit version and updated dependency ranges
Relates to https://github.com/wso2/api-manager/issues/3673

Introduce swagger.parser 2.1.25.wso2v2

---

kafka-avro-serializer/7.6.0.wso2v2/pom.xml
kafka-schema-registry-client/7.6.0.wso2v2/pom.xml
kafka-schema-serializer/7.6.0.wso2v2/pom.xml

Since WSO2 servers have separate guava jars in the classpath, the dependencies gets mixed when try to deploy Kafka connectors. Hence the guava is embedded inside the orbit bundles to resolve classloading issues.

Embedded guava as shaded inside kafka schema dependencies

---

bcpkix/1.80.0.wso2v1/pom.xml
bcprov/1.80.0.wso2v1/pom.xml
bctls/1.80.0.wso2v1/pom.xml
bcutil/1.80.0.wso2v1/pom.xml
pom.xml

- Add BouncyCastle `prov`, `pkix`, and `util` libraries of version 1.80.
- Add BouncyCastle `tls` library of version 1.80 using WSO2 fork containing custom modifications.

Add BouncyCastle 1.80

---

okhttp/4.11.0.wso2v2/pom.xml

- Address [CVE-2020-29582](https://github.com/advisories/GHSA-cqj8-47ch-rvvq)
- For the fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/9542
`okhttp` 4.11.0.wso2v2 added with `kotlin` version upgraded to 2.1.21

Add pom.xml for okhttp 4.11.0.wso2v2 bundle

---

okio/3.5.0.wso2v2/pom.xml

- Address [CVE-2020-29582](https://github.com/advisories/GHSA-cqj8-47ch-rvvq)
- For the fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/9542
`okio` 3.5.0.wso2v2 added with `kotlin` version upgraded to 2.1.21

Add pom.xml for okio 3.5.0.wso2v2 bundle

---

okhttp/4.12.0.wso2v3/pom.xml

- Address [CVE-2020-29582](https://github.com/advisories/GHSA-cqj8-47ch-rvvq)
- For the fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/9843
`okhttp` 4.12.0.wso2v3 added with `kotlin` version upgraded to 2.1.21

Add pom.xml for okhttp 4.12.0.wso2v3 bundle

---

zookeeper/3.9.3.wso2v1/pom.xml

- Address CVE-2024-51504
- For the fix of https://github.com/wso2-enterprise/wso2-apim-internal/issues/10016
Bumped `zookeeper` to version 3.9.3.wso2v1, updating `zookeeper` dependency to version 3.9.3.

Add pom.xml for Apache Zookeeper 3.9.3.wso2v1 bundle

---

openapi-generator/7.11.0.wso2v2/pom.xml

We need to $subject as the current `openapi-generator 7.11.0wso2v1` does not have the dependency `rgxgen` [1] which is required for python SDK generation of certain APIs created using openapi definitions with composed schemas.
Included the rgxgen (version 1.4) dependency, which is the latest version that is compatible with APIM 4.2.0
[1] https://mvnrepository.com/artifact/com.github.curious-odd-man/rgxgen/1.4

Introduce openapi-generator 7.11.0.wso2v2

---

ua-parser/1.6.1.wso2v2/pom.xml

Correction of `wso2v` version from **1.6.1.wso2v1** to **1.6.1.wso2v2** related to [[1]](https://github.com/wso2/orbit/pull/1229)
- [1] https://github.com/wso2/orbit/pull/1229

[Bundle][Bump] uap-java in ua-parser from 1.5.4.wso2v2 to 1.6.1.wso2v2 - Correcting the version

---

opensaml/2.6.6.wso2v9/pom.xml
opensaml/3.3.1.wso2v15/pom.xml

In the Orbit bundles opensaml:2.6.6.wso2v9 and opensaml:3.3.1.wso2v15, we upgraded esapi to version 2.7.0.0, which is the latest available version. However, this version includes transitive dependencies that have known vulnerabilities — specifically from commons-configuration and commons-lang.
We have already excluded commons-configuration in a previous update. With this PR, we are now excluding the vulnerable commons-lang dependency as well.

Exclude commons-lang from ESAPI in Opensaml Orbit Bundles 2.6.6.wso2v9 and 3.3.1.wso2v15

---

okhttp/4.12.0.wso2v4/pom.xml
okio/3.16.0.wso2v1/pom.xml

- **OkHttp 4.12.0.wso2v4**: Upgraded Kotlin (2.1.21→2.2.10) and MockWebServer (4.9.3→4.12.0)
- **Okio 3.16.0.wso2v1**: Upgraded from 3.9.0 with Kotlin (2.1.21→2.2.10)
- Aligned MockWebServer version with OkHttp for compatibility
- Updated Kotlin runtime to 2.2.10 for both bundles

Add okhttp 4.12.0.wso2v4 and okio 3.16.0.wso2v1 orbit bundles

---

azure-resourcemanager-apimanagement/2.0.0.wso2v2/pom.xml

These dependencies are added later due to an additional SDK method usage in the Azure Gateway manager to download the open api specification, which was previously done via raw REST APIs, which resulted in unexpected encoding issues since the sas link provided by Azure contained unsupported characters.

Add Azure Storage blob and Azure XML required by Azure gateway manager.
